var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(k,q,t){k!=Array.prototype&&k!=Object.prototype&&(k[q]=t.value)};$jscomp.getGlobal=function(k){return"undefined"!=typeof window&&window===k?k:"undefined"!=typeof global&&null!=global?global:k};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(k,q,t,x){if(q){t=$jscomp.global;k=k.split(".");for(x=0;x<k.length-1;x++){var J=k[x];J in t||(t[J]={});t=t[J]}k=k[k.length-1];x=t[k];q=q(x);q!=x&&null!=q&&$jscomp.defineProperty(t,k,{configurable:!0,writable:!0,value:q})}};
$jscomp.polyfill("Math.hypot",function(k){return k?k:function(k){if(2>arguments.length)return arguments.length?Math.abs(arguments[0]):0;var t,x,q;for(t=q=0;t<arguments.length;t++)q=Math.max(q,Math.abs(arguments[t]));if(1E100<q||1E-100>q){if(!q)return q;for(t=x=0;t<arguments.length;t++){var B=Number(arguments[t])/q;x+=B*B}return Math.sqrt(x)*q}for(t=x=0;t<arguments.length;t++)B=Number(arguments[t]),x+=B*B;return Math.sqrt(x)}},"es6","es3");
var keylist={},vertexShaderText="precision mediump float;\n\nattribute vec3 vertPosition;\nattribute vec3 vertColor;\nuniform mat4 mWorld;\nuniform mat4 mView;\nuniform mat4 mProj;\nvarying vec3 fragColor;\n\nvoid main()\n{\nfragColor = vertColor;\ngl_Position = vec4(vertPosition, 1.0);\n}",fragShaderText="precision mediump float;\nvarying vec3 fragColor;\nvoid main()\n{\ngl_FragColor = vec4(fragColor,1.0);\n}";
function main(){console.log("started main");var k=document.querySelector("#canvas1").getContext("webgl");k.clearColor(0,0,0,1);k.clear(k.COLOR_BUFFER_BIT);var q=k.createShader(k.VERTEX_SHADER),t=k.createShader(k.FRAGMENT_SHADER);k.shaderSource(q,vertexShaderText);k.shaderSource(t,fragShaderText);k.compileShader(q);k.compileShader(t);if(k.getShaderParameter(q,k.COMPILE_STATUS))if(k.getShaderParameter(t,k.COMPILE_STATUS)){var x=k.createProgram();k.attachShader(x,q);k.attachShader(x,t);k.linkProgram(x);
k.getProgramParameter(x,k.LINK_STATUS)||console.error("ERROR linking program",k.getProgramInfoLog(x));k.validateProgram(x);k.getProgramParameter(x,k.VALIDATE_STATUS)||console.error("ERROR validating",k.getProgramInfoLog(x));q=k.createBuffer();k.bindBuffer(k.ARRAY_BUFFER,q);k.bufferData(k.ARRAY_BUFFER,new Float32Array([0,.5,0,1,1,0,-.5,-.5,0,.7,0,.9,.5,-.5,0,.3,.5,.9]),k.STATIC_DRAW);q=k.getAttribLocation(x,"vertPosition");t=k.getAttribLocation(x,"vertColor");k.vertexAttribPointer(q,3,k.FLOAT,k.FALSE,
6*Float32Array.BYTES_PER_ELEMENT,0);k.vertexAttribPointer(t,3,k.FLOAT,k.FALSE,6*Float32Array.BYTES_PER_ELEMENT,3*Float32Array.BYTES_PER_ELEMENT);k.enableVertexAttribArray(q);k.enableVertexAttribArray(t);k.useProgram(x);q=k.getUniformLocation(x,"mWorld");t=k.getUniformLocation(x,"mView");var J=k.getUniformLocation(x,"mWProj"),B=new Float32Array(16),M=new Float32Array(16),O=new Float32Array(16);mat4.identity(O);mat4.identity(M);mat4.identity(B);k.uniformMatrix4fv(q,k.FALSE,O);k.uniformMatrix4fv(t,k.FALSE,
M);k.uniformMatrix4fv(J,k.FALSE,B);k.useProgram(x);k.drawArrays(k.TRIANGLES,0,3)}else console.error("ERROR compiling",k.getShaderInfoLog(t));else console.error("ERROR compiling",k.getShaderInfoLog(q))}function keypressed(k){keylist[k.key]="keydown"==k.type;keylist.s&&keylist.Alt&&main()};/*
 @fileoverview gl-matrix - High performance matrix and vector operations
@author Brandon Jones
@author Colin MacKenzie IV
@version 3.1.0

Copyright (c) 2015-2019, Brandon Jones, Colin MacKenzie IV.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

*/
(function(k,q){"object"===typeof exports&&"undefined"!==typeof module?q(exports):"function"===typeof define&&define.amd?define(["exports"],q):(k=k||self,q(k.glMatrix={}))})(this,function(k){function q(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];var g=c[0],h=c[1],l=c[2];c=c[3];a[0]=d*g+f*h;a[1]=e*g+b*h;a[2]=d*l+f*c;a[3]=e*l+b*c;return a}function t(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];return a}function x(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4];b=b[5];var l=c[0],m=c[1],
n=c[2],p=c[3],y=c[4];c=c[5];a[0]=d*l+f*m;a[1]=e*l+g*m;a[2]=d*n+f*p;a[3]=e*n+g*p;a[4]=d*y+f*c+h;a[5]=e*y+g*c+b;return a}function J(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];a[4]=b[4]-c[4];a[5]=b[5]-c[5];return a}function B(){var a=new v(9);v!=Float32Array&&(a[1]=0,a[2]=0,a[3]=0,a[5]=0,a[6]=0,a[7]=0);a[0]=1;a[4]=1;a[8]=1;return a}function M(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4],l=b[5],m=b[6],n=b[7];b=b[8];var p=c[0],y=c[1],r=c[2],k=c[3],u=c[4],w=c[5],v=c[6],C=c[7];c=
c[8];a[0]=p*d+y*g+r*m;a[1]=p*e+y*h+r*n;a[2]=p*f+y*l+r*b;a[3]=k*d+u*g+w*m;a[4]=k*e+u*h+w*n;a[5]=k*f+u*l+w*b;a[6]=v*d+C*g+c*m;a[7]=v*e+C*h+c*n;a[8]=v*f+C*l+c*b;return a}function O(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];a[4]=b[4]-c[4];a[5]=b[5]-c[5];a[6]=b[6]-c[6];a[7]=b[7]-c[7];a[8]=b[8]-c[8];return a}function ha(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}function ia(a,b,c){var d=b[0],
e=b[1],f=b[2],g=b[3],h=b[4],l=b[5],m=b[6],n=b[7],p=b[8],y=b[9],r=b[10],k=b[11],u=b[12],w=b[13],v=b[14];b=b[15];var C=c[0],q=c[1],t=c[2],z=c[3];a[0]=C*d+q*h+t*p+z*u;a[1]=C*e+q*l+t*y+z*w;a[2]=C*f+q*m+t*r+z*v;a[3]=C*g+q*n+t*k+z*b;C=c[4];q=c[5];t=c[6];z=c[7];a[4]=C*d+q*h+t*p+z*u;a[5]=C*e+q*l+t*y+z*w;a[6]=C*f+q*m+t*r+z*v;a[7]=C*g+q*n+t*k+z*b;C=c[8];q=c[9];t=c[10];z=c[11];a[8]=C*d+q*h+t*p+z*u;a[9]=C*e+q*l+t*y+z*w;a[10]=C*f+q*m+t*r+z*v;a[11]=C*g+q*n+t*k+z*b;C=c[12];q=c[13];t=c[14];z=c[15];a[12]=C*d+q*h+
t*p+z*u;a[13]=C*e+q*l+t*y+z*w;a[14]=C*f+q*m+t*r+z*v;a[15]=C*g+q*n+t*k+z*b;return a}function ja(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=d+d,l=e+e,m=f+f;b=d*h;var n=d*l;d*=m;var p=e*l;e*=m;f*=m;h*=g;l*=g;g*=m;a[0]=1-(p+f);a[1]=n+g;a[2]=d-l;a[3]=0;a[4]=n-g;a[5]=1-(b+f);a[6]=e+h;a[7]=0;a[8]=d+l;a[9]=e-h;a[10]=1-(b+p);a[11]=0;a[12]=c[0];a[13]=c[1];a[14]=c[2];a[15]=1;return a}function ka(a,b){a[0]=b[12];a[1]=b[13];a[2]=b[14];return a}function la(a,b){var c=b[4],d=b[5],e=b[6],f=b[8],g=b[9],h=b[10];a[0]=
Math.hypot(b[0],b[1],b[2]);a[1]=Math.hypot(c,d,e);a[2]=Math.hypot(f,g,h);return a}function ma(a,b){var c=new v(3);la(c,b);var d=1/c[0],e=1/c[1],f=1/c[2],g=b[0]*d;c=b[1]*e;var h=b[2]*f,l=b[4]*d,m=b[5]*e,n=b[6]*f;d*=b[8];e*=b[9];b=b[10]*f;f=g+m+b;0<f?(g=2*Math.sqrt(f+1),a[3]=.25*g,a[0]=(n-e)/g,a[1]=(d-h)/g,a[2]=(c-l)/g):g>m&&g>b?(g=2*Math.sqrt(1+g-m-b),a[3]=(n-e)/g,a[0]=.25*g,a[1]=(c+l)/g,a[2]=(d+h)/g):m>b?(g=2*Math.sqrt(1+m-g-b),a[3]=(d-h)/g,a[0]=(c+l)/g,a[1]=.25*g,a[2]=(n+e)/g):(g=2*Math.sqrt(1+b-
g-m),a[3]=(c-l)/g,a[0]=(d+h)/g,a[1]=(n+e)/g,a[2]=.25*g);return a}function na(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];a[4]=b[4]-c[4];a[5]=b[5]-c[5];a[6]=b[6]-c[6];a[7]=b[7]-c[7];a[8]=b[8]-c[8];a[9]=b[9]-c[9];a[10]=b[10]-c[10];a[11]=b[11]-c[11];a[12]=b[12]-c[12];a[13]=b[13]-c[13];a[14]=b[14]-c[14];a[15]=b[15]-c[15];return a}function Y(){var a=new v(3);v!=Float32Array&&(a[0]=0,a[1]=0,a[2]=0);return a}function Z(a){return Math.hypot(a[0],a[1],a[2])}function P(a,b,c){var d=new v(3);
d[0]=a;d[1]=b;d[2]=c;return d}function oa(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];return a}function pa(a,b,c){a[0]=b[0]*c[0];a[1]=b[1]*c[1];a[2]=b[2]*c[2];return a}function qa(a,b,c){a[0]=b[0]/c[0];a[1]=b[1]/c[1];a[2]=b[2]/c[2];return a}function ra(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1],b[2]-a[2])}function sa(a,b){var c=b[0]-a[0],d=b[1]-a[1];a=b[2]-a[2];return c*c+d*d+a*a}function ta(a){var b=a[0],c=a[1];a=a[2];return b*b+c*c+a*a}function S(a,b){var c=b[0],d=b[1],e=b[2];c=c*c+d*d+
e*e;0<c&&(c=1/Math.sqrt(c));a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;return a}function aa(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}function T(a,b,c){var d=b[0],e=b[1];b=b[2];var f=c[0],g=c[1];c=c[2];a[0]=e*c-b*g;a[1]=b*f-d*c;a[2]=d*g-e*f;return a}function ua(){var a=new v(4);v!=Float32Array&&(a[0]=0,a[1]=0,a[2]=0,a[3]=0);return a}function va(a){var b=new v(4);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b}function wa(a,b,c,d){var e=new v(4);e[0]=a;e[1]=b;e[2]=c;e[3]=d;return e}function U(a,b){a[0]=
b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];return a}function xa(a,b,c,d,e){a[0]=b;a[1]=c;a[2]=d;a[3]=e;return a}function ya(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];return a}function za(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];return a}function Aa(a,b,c){a[0]=b[0]*c[0];a[1]=b[1]*c[1];a[2]=b[2]*c[2];a[3]=b[3]*c[3];return a}function Ba(a,b,c){a[0]=b[0]/c[0];a[1]=b[1]/c[1];a[2]=b[2]/c[2];a[3]=b[3]/c[3];return a}function ba(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=
b[2]*c;a[3]=b[3]*c;return a}function Ca(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1],b[2]-a[2],b[3]-a[3])}function Da(a,b){var c=b[0]-a[0],d=b[1]-a[1],e=b[2]-a[2];a=b[3]-a[3];return c*c+d*d+e*e+a*a}function L(a){return Math.hypot(a[0],a[1],a[2],a[3])}function K(a){var b=a[0],c=a[1],d=a[2];a=a[3];return b*b+c*c+d*d+a*a}function V(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];var f=c*c+d*d+e*e+b*b;0<f&&(f=1/Math.sqrt(f));a[0]=c*f;a[1]=d*f;a[2]=e*f;a[3]=b*f;return a}function Q(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*
b[2]+a[3]*b[3]}function Ea(a,b,c,d){var e=b[0],f=b[1],g=b[2];b=b[3];a[0]=e+d*(c[0]-e);a[1]=f+d*(c[1]-f);a[2]=g+d*(c[2]-g);a[3]=b+d*(c[3]-b);return a}function Fa(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]}function Ga(a,b){var c=a[0],d=a[1],e=a[2];a=a[3];var f=b[0],g=b[1],h=b[2];b=b[3];return Math.abs(c-f)<=1E-6*Math.max(1,Math.abs(c),Math.abs(f))&&Math.abs(d-g)<=1E-6*Math.max(1,Math.abs(d),Math.abs(g))&&Math.abs(e-h)<=1E-6*Math.max(1,Math.abs(e),Math.abs(h))&&Math.abs(a-b)<=1E-6*
Math.max(1,Math.abs(a),Math.abs(b))}function W(){var a=new v(4);v!=Float32Array&&(a[0]=0,a[1]=0,a[2]=0);a[3]=1;return a}function Ha(a,b,c){c*=.5;var d=Math.sin(c);a[0]=d*b[0];a[1]=d*b[1];a[2]=d*b[2];a[3]=Math.cos(c);return a}function Ia(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];var g=c[0],h=c[1],l=c[2];c=c[3];a[0]=d*c+b*g+e*l-f*h;a[1]=e*c+b*h+f*g-d*l;a[2]=f*c+b*l+d*h-e*g;a[3]=b*c-d*g-e*h-f*l;return a}function Ja(a,b,c){c*=.5;var d=b[0],e=b[1],f=b[2];b=b[3];var g=Math.sin(c);c=Math.cos(c);a[0]=d*c+b*
g;a[1]=e*c+f*g;a[2]=f*c-e*g;a[3]=b*c-d*g;return a}function Ka(a,b,c){c*=.5;var d=b[0],e=b[1],f=b[2];b=b[3];var g=Math.sin(c);c=Math.cos(c);a[0]=d*c-f*g;a[1]=e*c+b*g;a[2]=f*c+d*g;a[3]=b*c-e*g;return a}function La(a,b,c){c*=.5;var d=b[0],e=b[1],f=b[2];b=b[3];var g=Math.sin(c);c=Math.cos(c);a[0]=d*c+e*g;a[1]=e*c-d*g;a[2]=f*c+b*g;a[3]=b*c-f*g;return a}function Ma(a,b){var c=b[0],d=b[1],e=b[2],f=Math.sqrt(c*c+d*d+e*e);b=Math.exp(b[3]);var g=0<f?b*Math.sin(f)/f:0;a[0]=c*g;a[1]=d*g;a[2]=e*g;a[3]=b*Math.cos(f);
return a}function Na(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];var f=Math.sqrt(c*c+d*d+e*e);f=0<f?Math.atan2(f,b)/f:0;a[0]=c*f;a[1]=d*f;a[2]=e*f;a[3]=.5*Math.log(c*c+d*d+e*e+b*b);return a}function X(a,b,c,d){var e=b[0],f=b[1],g=b[2];b=b[3];var h=c[0],l=c[1],m=c[2];c=c[3];var n=e*h+f*l+g*m+b*c;0>n&&(n=-n,h=-h,l=-l,m=-m,c=-c);if(1E-6<1-n){var p=Math.acos(n);var y=Math.sin(p);n=Math.sin((1-d)*p)/y;d=Math.sin(d*p)/y}else n=1-d;a[0]=n*e+d*h;a[1]=n*f+d*l;a[2]=n*g+d*m;a[3]=n*b+d*c;return a}function Oa(a,b){var c=
b[0]+b[4]+b[8];if(0<c)c=Math.sqrt(c+1),a[3]=.5*c,c=.5/c,a[0]=(b[5]-b[7])*c,a[1]=(b[6]-b[2])*c,a[2]=(b[1]-b[3])*c;else{var d=0;b[4]>b[0]&&(d=1);b[8]>b[3*d+d]&&(d=2);var e=(d+1)%3,f=(d+2)%3;c=Math.sqrt(b[3*d+d]-b[3*e+e]-b[3*f+f]+1);a[d]=.5*c;c=.5/c;a[3]=(b[3*e+f]-b[3*f+e])*c;a[e]=(b[3*e+d]+b[3*d+e])*c;a[f]=(b[3*f+d]+b[3*d+f])*c}return a}function Pa(a,b,c){var d=.5*c[0],e=.5*c[1];c=.5*c[2];var f=b[0],g=b[1],h=b[2];b=b[3];a[0]=f;a[1]=g;a[2]=h;a[3]=b;a[4]=d*b+e*h-c*g;a[5]=e*b+c*f-d*h;a[6]=c*b+d*g-e*f;
a[7]=-d*f-e*g-c*h;return a}function Qa(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];return a}function Ra(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=c[4],l=c[5],m=c[6],n=c[7],p=b[4],y=b[5],r=b[6];b=b[7];var k=c[0],u=c[1],w=c[2];c=c[3];a[0]=d*c+g*k+e*w-f*u;a[1]=e*c+g*u+f*k-d*w;a[2]=f*c+g*w+d*u-e*k;a[3]=g*c-d*k-e*u-f*w;a[4]=d*n+g*h+e*m-f*l+p*c+b*k+y*w-r*u;a[5]=e*n+g*l+f*h-d*m+y*c+b*u+r*k-p*w;a[6]=f*n+g*m+d*l-e*h+r*c+b*w+p*u-y*k;a[7]=g*n-d*h-e*l-f*m+b*c-p*k-y*u-r*
w;return a}function Sa(){var a=new v(2);v!=Float32Array&&(a[0]=0,a[1]=0);return a}function Ta(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];return a}function Ua(a,b,c){a[0]=b[0]*c[0];a[1]=b[1]*c[1];return a}function Va(a,b,c){a[0]=b[0]/c[0];a[1]=b[1]/c[1];return a}function Wa(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1])}function Xa(a,b){var c=b[0]-a[0];a=b[1]-a[1];return c*c+a*a}function Ya(a){return Math.hypot(a[0],a[1])}function Za(a){var b=a[0];a=a[1];return b*b+a*a}var v="undefined"!==typeof Float32Array?
Float32Array:Array,A=Math.random,$a=Math.PI/180;Math.hypot||(Math.hypot=function(){for(var a=0,b=arguments.length;b--;)a+=arguments[b]*arguments[b];return Math.sqrt(a)});var ab=Object.freeze({EPSILON:1E-6,get ARRAY_TYPE(){return v},RANDOM:A,setMatrixArrayType:function(a){v=a},toRadian:function(a){return a*$a},equals:function(a,b){return Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))}}),bb=Object.freeze({create:function(){var a=new v(4);v!=Float32Array&&(a[1]=0,a[2]=0);a[0]=1;a[3]=1;return a},
clone:function(a){var b=new v(4);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];return a},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=1;return a},fromValues:function(a,b,c,d){var e=new v(4);e[0]=a;e[1]=b;e[2]=c;e[3]=d;return e},set:function(a,b,c,d,e){a[0]=b;a[1]=c;a[2]=d;a[3]=e;return a},transpose:function(a,b){if(a===b){var c=b[1];a[1]=b[2];a[2]=c}else a[0]=b[0],a[1]=b[2],a[2]=b[1],a[3]=b[3];return a},invert:function(a,b){var c=b[0],
d=b[1],e=b[2];b=b[3];var f=c*b-e*d;if(!f)return null;f=1/f;a[0]=b*f;a[1]=-d*f;a[2]=-e*f;a[3]=c*f;return a},adjoint:function(a,b){var c=b[0];a[0]=b[3];a[1]=-b[1];a[2]=-b[2];a[3]=c;return a},determinant:function(a){return a[0]*a[3]-a[2]*a[1]},multiply:q,rotate:function(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];var g=Math.sin(c);c=Math.cos(c);a[0]=d*c+f*g;a[1]=e*c+b*g;a[2]=d*-g+f*c;a[3]=e*-g+b*c;return a},scale:function(a,b,c){var d=b[1],e=b[2],f=b[3],g=c[0];c=c[1];a[0]=b[0]*g;a[1]=d*g;a[2]=e*c;a[3]=f*
c;return a},fromRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=c;a[2]=-c;a[3]=b;return a},fromScaling:function(a,b){a[0]=b[0];a[1]=0;a[2]=0;a[3]=b[1];return a},str:function(a){return"mat2("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"},frob:function(a){return Math.hypot(a[0],a[1],a[2],a[3])},LDU:function(a,b,c,d){a[2]=d[2]/d[0];c[0]=d[0];c[1]=d[1];c[3]=d[3]-a[2]*c[1];return[a,b,c]},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];return a},subtract:t,exactEquals:function(a,
b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]},equals:function(a,b){var c=a[0],d=a[1],e=a[2];a=a[3];var f=b[0],g=b[1],h=b[2];b=b[3];return Math.abs(c-f)<=1E-6*Math.max(1,Math.abs(c),Math.abs(f))&&Math.abs(d-g)<=1E-6*Math.max(1,Math.abs(d),Math.abs(g))&&Math.abs(e-h)<=1E-6*Math.max(1,Math.abs(e),Math.abs(h))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},multiplyScalar:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;return a},multiplyScalarAndAdd:function(a,
b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;return a},mul:q,sub:t}),cb=Object.freeze({create:function(){var a=new v(6);v!=Float32Array&&(a[1]=0,a[2]=0,a[4]=0,a[5]=0);a[0]=1;a[3]=1;return a},clone:function(a){var b=new v(6);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];return b},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];return a},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=1;a[4]=0;a[5]=0;return a},fromValues:function(a,
b,c,d,e,f){var g=new v(6);g[0]=a;g[1]=b;g[2]=c;g[3]=d;g[4]=e;g[5]=f;return g},set:function(a,b,c,d,e,f,g){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=f;a[5]=g;return a},invert:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4];b=b[5];var h=c*f-d*e;if(!h)return null;h=1/h;a[0]=f*h;a[1]=-d*h;a[2]=-e*h;a[3]=c*h;a[4]=(e*b-f*g)*h;a[5]=(d*g-c*b)*h;return a},determinant:function(a){return a[0]*a[3]-a[1]*a[2]},multiply:x,rotate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4];b=b[5];var l=Math.sin(c);c=Math.cos(c);
a[0]=d*c+f*l;a[1]=e*c+g*l;a[2]=d*-l+f*c;a[3]=e*-l+g*c;a[4]=h;a[5]=b;return a},scale:function(a,b,c){var d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],l=c[0];c=c[1];a[0]=b[0]*l;a[1]=d*l;a[2]=e*c;a[3]=f*c;a[4]=g;a[5]=h;return a},translate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4];b=b[5];var l=c[0];c=c[1];a[0]=d;a[1]=e;a[2]=f;a[3]=g;a[4]=d*l+f*c+h;a[5]=e*l+g*c+b;return a},fromRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=c;a[2]=-c;a[3]=b;a[4]=0;a[5]=0;return a},fromScaling:function(a,
b){a[0]=b[0];a[1]=0;a[2]=0;a[3]=b[1];a[4]=0;a[5]=0;return a},fromTranslation:function(a,b){a[0]=1;a[1]=0;a[2]=0;a[3]=1;a[4]=b[0];a[5]=b[1];return a},str:function(a){return"mat2d("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+")"},frob:function(a){return Math.hypot(a[0],a[1],a[2],a[3],a[4],a[5],1)},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];return a},subtract:J,multiplyScalar:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*
c;a[3]=b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;return a},multiplyScalarAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;a[4]=b[4]+c[4]*d;a[5]=b[5]+c[5]*d;return a},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===b[4]&&a[5]===b[5]},equals:function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4];a=a[5];var h=b[0],l=b[1],m=b[2],n=b[3],p=b[4];b=b[5];return Math.abs(c-h)<=1E-6*Math.max(1,Math.abs(c),Math.abs(h))&&Math.abs(d-l)<=
1E-6*Math.max(1,Math.abs(d),Math.abs(l))&&Math.abs(e-m)<=1E-6*Math.max(1,Math.abs(e),Math.abs(m))&&Math.abs(f-n)<=1E-6*Math.max(1,Math.abs(f),Math.abs(n))&&Math.abs(g-p)<=1E-6*Math.max(1,Math.abs(g),Math.abs(p))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},mul:x,sub:J}),db=Object.freeze({create:B,fromMat4:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[4];a[4]=b[5];a[5]=b[6];a[6]=b[8];a[7]=b[9];a[8]=b[10];return a},clone:function(a){var b=new v(9);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=
a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];return a},fromValues:function(a,b,c,d,e,f,g,h,l){var m=new v(9);m[0]=a;m[1]=b;m[2]=c;m[3]=d;m[4]=e;m[5]=f;m[6]=g;m[7]=h;m[8]=l;return m},set:function(a,b,c,d,e,f,g,h,l,m){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=f;a[5]=g;a[6]=h;a[7]=l;a[8]=m;return a},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;
return a},transpose:function(a,b){if(a===b){var c=b[1],d=b[2],e=b[5];a[1]=b[3];a[2]=b[6];a[3]=c;a[5]=b[7];a[6]=d;a[7]=e}else a[0]=b[0],a[1]=b[3],a[2]=b[6],a[3]=b[1],a[4]=b[4],a[5]=b[7],a[6]=b[2],a[7]=b[5],a[8]=b[8];return a},invert:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],l=b[6],m=b[7];b=b[8];var n=b*g-h*m,p=-b*f+h*l,k=m*f-g*l,r=c*n+d*p+e*k;if(!r)return null;r=1/r;a[0]=n*r;a[1]=(-b*d+e*m)*r;a[2]=(h*d-e*g)*r;a[3]=p*r;a[4]=(b*c-e*l)*r;a[5]=(-h*c+e*f)*r;a[6]=k*r;a[7]=(-m*c+d*l)*r;
a[8]=(g*c-d*f)*r;return a},adjoint:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],l=b[6],m=b[7];b=b[8];a[0]=g*b-h*m;a[1]=e*m-d*b;a[2]=d*h-e*g;a[3]=h*l-f*b;a[4]=c*b-e*l;a[5]=e*f-c*h;a[6]=f*m-g*l;a[7]=d*l-c*m;a[8]=c*g-d*f;return a},determinant:function(a){var b=a[3],c=a[4],d=a[5],e=a[6],f=a[7],g=a[8];return a[0]*(g*c-d*f)+a[1]*(-g*b+d*e)+a[2]*(f*b-c*e)},multiply:M,translate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4],l=b[5],m=b[6],n=b[7];b=b[8];var p=c[0];c=c[1];a[0]=d;a[1]=
e;a[2]=f;a[3]=g;a[4]=h;a[5]=l;a[6]=p*d+c*g+m;a[7]=p*e+c*h+n;a[8]=p*f+c*l+b;return a},rotate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4],l=b[5],m=b[6],n=b[7];b=b[8];var p=Math.sin(c);c=Math.cos(c);a[0]=c*d+p*g;a[1]=c*e+p*h;a[2]=c*f+p*l;a[3]=c*g-p*d;a[4]=c*h-p*e;a[5]=c*l-p*f;a[6]=m;a[7]=n;a[8]=b;return a},scale:function(a,b,c){var d=c[0];c=c[1];a[0]=d*b[0];a[1]=d*b[1];a[2]=d*b[2];a[3]=c*b[3];a[4]=c*b[4];a[5]=c*b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];return a},fromTranslation:function(a,b){a[0]=
1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=b[0];a[7]=b[1];a[8]=1;return a},fromRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=c;a[2]=0;a[3]=-c;a[4]=b;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},fromScaling:function(a,b){a[0]=b[0];a[1]=0;a[2]=0;a[3]=0;a[4]=b[1];a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},fromMat2d:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=0;a[3]=b[2];a[4]=b[3];a[5]=0;a[6]=b[4];a[7]=b[5];a[8]=1;return a},fromQuat:function(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];var f=c+c,g=d+d,h=e+
e;c*=f;var l=d*f;d*=g;var m=e*f,n=e*g;e*=h;f*=b;g*=b;b*=h;a[0]=1-d-e;a[3]=l-b;a[6]=m+g;a[1]=l+b;a[4]=1-c-e;a[7]=n-f;a[2]=m-g;a[5]=n+f;a[8]=1-c-d;return a},normalFromMat4:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],l=b[6],m=b[7],n=b[8],p=b[9],k=b[10],r=b[11],q=b[12],u=b[13],w=b[14];b=b[15];var t=c*h-d*g,v=c*l-e*g,x=c*m-f*g,N=d*l-e*h,z=d*m-f*h,E=e*m-f*l,F=n*u-p*q,G=n*w-k*q;n=n*b-r*q;var H=p*w-k*u;p=p*b-r*u;k=k*b-r*w;r=t*k-v*p+x*H+N*n-z*G+E*F;if(!r)return null;r=1/r;a[0]=(h*k-l*p+m*H)*
r;a[1]=(l*n-g*k-m*G)*r;a[2]=(g*p-h*n+m*F)*r;a[3]=(e*p-d*k-f*H)*r;a[4]=(c*k-e*n+f*G)*r;a[5]=(d*n-c*p-f*F)*r;a[6]=(u*E-w*z+b*N)*r;a[7]=(w*x-q*E-b*v)*r;a[8]=(q*z-u*x+b*t)*r;return a},projection:function(a,b,c){a[0]=2/b;a[1]=0;a[2]=0;a[3]=0;a[4]=-2/c;a[5]=0;a[6]=-1;a[7]=1;a[8]=1;return a},str:function(a){return"mat3("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+")"},frob:function(a){return Math.hypot(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8])},add:function(a,
b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];a[6]=b[6]+c[6];a[7]=b[7]+c[7];a[8]=b[8]+c[8];return a},subtract:O,multiplyScalar:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;a[6]=b[6]*c;a[7]=b[7]*c;a[8]=b[8]*c;return a},multiplyScalarAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;a[4]=b[4]+c[4]*d;a[5]=b[5]+c[5]*d;a[6]=b[6]+c[6]*d;a[7]=b[7]+c[7]*d;a[8]=b[8]+c[8]*d;
return a},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===b[4]&&a[5]===b[5]&&a[6]===b[6]&&a[7]===b[7]&&a[8]===b[8]},equals:function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],l=a[6],m=a[7];a=a[8];var n=b[0],p=b[1],k=b[2],r=b[3],q=b[4],u=b[5],w=b[6],t=b[7];b=b[8];return Math.abs(c-n)<=1E-6*Math.max(1,Math.abs(c),Math.abs(n))&&Math.abs(d-p)<=1E-6*Math.max(1,Math.abs(d),Math.abs(p))&&Math.abs(e-k)<=1E-6*Math.max(1,Math.abs(e),Math.abs(k))&&Math.abs(f-
r)<=1E-6*Math.max(1,Math.abs(f),Math.abs(r))&&Math.abs(g-q)<=1E-6*Math.max(1,Math.abs(g),Math.abs(q))&&Math.abs(h-u)<=1E-6*Math.max(1,Math.abs(h),Math.abs(u))&&Math.abs(l-w)<=1E-6*Math.max(1,Math.abs(l),Math.abs(w))&&Math.abs(m-t)<=1E-6*Math.max(1,Math.abs(m),Math.abs(t))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},mul:M,sub:O}),eb=Object.freeze({create:function(){var a=new v(16);v!=Float32Array&&(a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[11]=0,a[12]=0,a[13]=0,a[14]=
0);a[0]=1;a[5]=1;a[10]=1;a[15]=1;return a},clone:function(a){var b=new v(16);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];a[9]=b[9];a[10]=b[10];a[11]=b[11];a[12]=b[12];a[13]=b[13];a[14]=b[14];a[15]=b[15];return a},fromValues:function(a,b,c,d,e,f,g,h,l,m,n,
p,k,r,q,u){var y=new v(16);y[0]=a;y[1]=b;y[2]=c;y[3]=d;y[4]=e;y[5]=f;y[6]=g;y[7]=h;y[8]=l;y[9]=m;y[10]=n;y[11]=p;y[12]=k;y[13]=r;y[14]=q;y[15]=u;return y},set:function(a,b,c,d,e,f,g,h,l,m,n,p,k,r,q,u,w){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=f;a[5]=g;a[6]=h;a[7]=l;a[8]=m;a[9]=n;a[10]=p;a[11]=k;a[12]=r;a[13]=q;a[14]=u;a[15]=w;return a},identity:ha,transpose:function(a,b){if(a===b){var c=b[1],d=b[2],e=b[3],f=b[6],g=b[7],h=b[11];a[1]=b[4];a[2]=b[8];a[3]=b[12];a[4]=c;a[6]=b[9];a[7]=b[13];a[8]=d;a[9]=f;a[11]=
b[14];a[12]=e;a[13]=g;a[14]=h}else a[0]=b[0],a[1]=b[4],a[2]=b[8],a[3]=b[12],a[4]=b[1],a[5]=b[5],a[6]=b[9],a[7]=b[13],a[8]=b[2],a[9]=b[6],a[10]=b[10],a[11]=b[14],a[12]=b[3],a[13]=b[7],a[14]=b[11],a[15]=b[15];return a},invert:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],l=b[6],m=b[7],n=b[8],p=b[9],k=b[10],r=b[11],q=b[12],u=b[13],w=b[14];b=b[15];var t=c*h-d*g,v=c*l-e*g,x=c*m-f*g,N=d*l-e*h,z=d*m-f*h,E=e*m-f*l,F=n*u-p*q,G=n*w-k*q,H=n*b-r*q,I=p*w-k*u,B=p*b-r*u,A=k*b-r*w,D=t*A-v*B+x*I+N*H-
z*G+E*F;if(!D)return null;D=1/D;a[0]=(h*A-l*B+m*I)*D;a[1]=(e*B-d*A-f*I)*D;a[2]=(u*E-w*z+b*N)*D;a[3]=(k*z-p*E-r*N)*D;a[4]=(l*H-g*A-m*G)*D;a[5]=(c*A-e*H+f*G)*D;a[6]=(w*x-q*E-b*v)*D;a[7]=(n*E-k*x+r*v)*D;a[8]=(g*B-h*H+m*F)*D;a[9]=(d*H-c*B-f*F)*D;a[10]=(q*z-u*x+b*t)*D;a[11]=(p*x-n*z-r*t)*D;a[12]=(h*G-g*I-l*F)*D;a[13]=(c*I-d*G+e*F)*D;a[14]=(u*v-q*N-w*t)*D;a[15]=(n*N-p*v+k*t)*D;return a},adjoint:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],l=b[6],m=b[7],n=b[8],p=b[9],k=b[10],r=b[11],q=b[12],
u=b[13],w=b[14];b=b[15];a[0]=h*(k*b-r*w)-p*(l*b-m*w)+u*(l*r-m*k);a[1]=-(d*(k*b-r*w)-p*(e*b-f*w)+u*(e*r-f*k));a[2]=d*(l*b-m*w)-h*(e*b-f*w)+u*(e*m-f*l);a[3]=-(d*(l*r-m*k)-h*(e*r-f*k)+p*(e*m-f*l));a[4]=-(g*(k*b-r*w)-n*(l*b-m*w)+q*(l*r-m*k));a[5]=c*(k*b-r*w)-n*(e*b-f*w)+q*(e*r-f*k);a[6]=-(c*(l*b-m*w)-g*(e*b-f*w)+q*(e*m-f*l));a[7]=c*(l*r-m*k)-g*(e*r-f*k)+n*(e*m-f*l);a[8]=g*(p*b-r*u)-n*(h*b-m*u)+q*(h*r-m*p);a[9]=-(c*(p*b-r*u)-n*(d*b-f*u)+q*(d*r-f*p));a[10]=c*(h*b-m*u)-g*(d*b-f*u)+q*(d*m-f*h);a[11]=-(c*
(h*r-m*p)-g*(d*r-f*p)+n*(d*m-f*h));a[12]=-(g*(p*w-k*u)-n*(h*w-l*u)+q*(h*k-l*p));a[13]=c*(p*w-k*u)-n*(d*w-e*u)+q*(d*k-e*p);a[14]=-(c*(h*w-l*u)-g*(d*w-e*u)+q*(d*l-e*h));a[15]=c*(h*k-l*p)-g*(d*k-e*p)+n*(d*l-e*h);return a},determinant:function(a){var b=a[0],c=a[1],d=a[2],e=a[3],f=a[4],g=a[5],h=a[6],l=a[7],m=a[8],n=a[9],p=a[10],k=a[11],r=a[12],q=a[13],u=a[14];a=a[15];return(b*g-c*f)*(p*a-k*u)-(b*h-d*f)*(n*a-k*q)+(b*l-e*f)*(n*u-p*q)+(c*h-d*g)*(m*a-k*r)-(c*l-e*g)*(m*u-p*r)+(d*l-e*h)*(m*q-n*r)},multiply:ia,
translate:function(a,b,c){var d=c[0],e=c[1];c=c[2];if(b===a)a[12]=b[0]*d+b[4]*e+b[8]*c+b[12],a[13]=b[1]*d+b[5]*e+b[9]*c+b[13],a[14]=b[2]*d+b[6]*e+b[10]*c+b[14],a[15]=b[3]*d+b[7]*e+b[11]*c+b[15];else{var f=b[0];var g=b[1];var h=b[2];var l=b[3];var m=b[4];var n=b[5];var p=b[6];var k=b[7];var r=b[8];var q=b[9];var u=b[10];var w=b[11];a[0]=f;a[1]=g;a[2]=h;a[3]=l;a[4]=m;a[5]=n;a[6]=p;a[7]=k;a[8]=r;a[9]=q;a[10]=u;a[11]=w;a[12]=f*d+m*e+r*c+b[12];a[13]=g*d+n*e+q*c+b[13];a[14]=h*d+p*e+u*c+b[14];a[15]=l*d+
k*e+w*c+b[15]}return a},scale:function(a,b,c){var d=c[0],e=c[1];c=c[2];a[0]=b[0]*d;a[1]=b[1]*d;a[2]=b[2]*d;a[3]=b[3]*d;a[4]=b[4]*e;a[5]=b[5]*e;a[6]=b[6]*e;a[7]=b[7]*e;a[8]=b[8]*c;a[9]=b[9]*c;a[10]=b[10]*c;a[11]=b[11]*c;a[12]=b[12];a[13]=b[13];a[14]=b[14];a[15]=b[15];return a},rotate:function(a,b,c,d){var e=d[0],f=d[1];d=d[2];var g=Math.hypot(e,f,d);if(1E-6>g)return null;g=1/g;e*=g;f*=g;d*=g;var h=Math.sin(c);var l=Math.cos(c);var m=1-l;c=b[0];g=b[1];var n=b[2];var k=b[3];var q=b[4];var r=b[5];var t=
b[6];var u=b[7];var w=b[8];var v=b[9];var x=b[10];var B=b[11];var A=e*e*m+l;var z=f*e*m+d*h;var E=d*e*m-f*h;var F=e*f*m-d*h;var G=f*f*m+l;var H=d*f*m+e*h;var I=e*d*m+f*h;e=f*d*m-e*h;f=d*d*m+l;a[0]=c*A+q*z+w*E;a[1]=g*A+r*z+v*E;a[2]=n*A+t*z+x*E;a[3]=k*A+u*z+B*E;a[4]=c*F+q*G+w*H;a[5]=g*F+r*G+v*H;a[6]=n*F+t*G+x*H;a[7]=k*F+u*G+B*H;a[8]=c*I+q*e+w*f;a[9]=g*I+r*e+v*f;a[10]=n*I+t*e+x*f;a[11]=k*I+u*e+B*f;b!==a&&(a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);return a},rotateX:function(a,b,c){var d=Math.sin(c);
c=Math.cos(c);var e=b[4],f=b[5],g=b[6],h=b[7],l=b[8],m=b[9],n=b[10],k=b[11];b!==a&&(a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);a[4]=e*c+l*d;a[5]=f*c+m*d;a[6]=g*c+n*d;a[7]=h*c+k*d;a[8]=l*c-e*d;a[9]=m*c-f*d;a[10]=n*c-g*d;a[11]=k*c-h*d;return a},rotateY:function(a,b,c){var d=Math.sin(c);c=Math.cos(c);var e=b[0],f=b[1],g=b[2],h=b[3],l=b[8],m=b[9],n=b[10],k=b[11];b!==a&&(a[4]=b[4],a[5]=b[5],a[6]=b[6],a[7]=b[7],a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);
a[0]=e*c-l*d;a[1]=f*c-m*d;a[2]=g*c-n*d;a[3]=h*c-k*d;a[8]=e*d+l*c;a[9]=f*d+m*c;a[10]=g*d+n*c;a[11]=h*d+k*c;return a},rotateZ:function(a,b,c){var d=Math.sin(c);c=Math.cos(c);var e=b[0],f=b[1],g=b[2],h=b[3],l=b[4],m=b[5],n=b[6],k=b[7];b!==a&&(a[8]=b[8],a[9]=b[9],a[10]=b[10],a[11]=b[11],a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);a[0]=e*c+l*d;a[1]=f*c+m*d;a[2]=g*c+n*d;a[3]=h*c+k*d;a[4]=l*c-e*d;a[5]=m*c-f*d;a[6]=n*c-g*d;a[7]=k*c-h*d;return a},fromTranslation:function(a,b){a[0]=1;a[1]=0;a[2]=0;a[3]=
0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=b[0];a[13]=b[1];a[14]=b[2];a[15]=1;return a},fromScaling:function(a,b){a[0]=b[0];a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b[1];a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=b[2];a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromRotation:function(a,b,c){var d=c[0],e=c[1];c=c[2];var f=Math.hypot(d,e,c);if(1E-6>f)return null;f=1/f;d*=f;e*=f;c*=f;f=Math.sin(b);b=Math.cos(b);var g=1-b;a[0]=d*d*g+b;a[1]=e*d*g+c*f;a[2]=c*d*g-e*f;a[3]=0;a[4]=d*e*g-c*f;a[5]=
e*e*g+b;a[6]=c*e*g+d*f;a[7]=0;a[8]=d*c*g+e*f;a[9]=e*c*g-d*f;a[10]=c*c*g+b;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromXRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b;a[6]=c;a[7]=0;a[8]=0;a[9]=-c;a[10]=b;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromYRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=0;a[2]=-c;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=c;a[9]=0;a[10]=b;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},
fromZRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=c;a[2]=0;a[3]=0;a[4]=-c;a[5]=b;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromRotationTranslation:ja,fromQuat2:function(a,b){var c=new v(3),d=-b[0],e=-b[1],f=-b[2],g=b[3],h=b[4],l=b[5],m=b[6],n=b[7],k=d*d+e*e+f*f+g*g;0<k?(c[0]=2*(h*g+n*d+l*f-m*e)/k,c[1]=2*(l*g+n*e+m*d-h*f)/k,c[2]=2*(m*g+n*f+h*e-l*d)/k):(c[0]=2*(h*g+n*d+l*f-m*e),c[1]=2*(l*g+n*e+m*d-h*f),c[2]=2*(m*g+n*f+h*e-l*d));ja(a,
b,c);return a},getTranslation:ka,getScaling:la,getRotation:ma,fromRotationTranslationScale:function(a,b,c,d){var e=b[0],f=b[1],g=b[2],h=b[3],l=e+e,m=f+f,n=g+g;b=e*l;var k=e*m;e*=n;var q=f*m;f*=n;g*=n;l*=h;m*=h;h*=n;n=d[0];var r=d[1];d=d[2];a[0]=(1-(q+g))*n;a[1]=(k+h)*n;a[2]=(e-m)*n;a[3]=0;a[4]=(k-h)*r;a[5]=(1-(b+g))*r;a[6]=(f+l)*r;a[7]=0;a[8]=(e+m)*d;a[9]=(f-l)*d;a[10]=(1-(b+q))*d;a[11]=0;a[12]=c[0];a[13]=c[1];a[14]=c[2];a[15]=1;return a},fromRotationTranslationScaleOrigin:function(a,b,c,d,e){var f=
b[0],g=b[1],h=b[2],l=b[3],m=f+f,n=g+g,k=h+h;b=f*m;var q=f*n,r=f*k;f=g*n;g*=k;var t=h*k;h=l*m;n*=l;var u=l*k,w=d[0],v=d[1];k=d[2];d=e[0];l=e[1];e=e[2];m=(1-(f+t))*w;var x=(q+u)*w;w*=r-n;q=(q-u)*v;t=(1-(b+t))*v;v*=g+h;r=(r+n)*k;g=(g-h)*k;b=(1-(b+f))*k;a[0]=m;a[1]=x;a[2]=w;a[3]=0;a[4]=q;a[5]=t;a[6]=v;a[7]=0;a[8]=r;a[9]=g;a[10]=b;a[11]=0;a[12]=c[0]+d-(m*d+q*l+r*e);a[13]=c[1]+l-(x*d+t*l+g*e);a[14]=c[2]+e-(w*d+v*l+b*e);a[15]=1;return a},fromQuat:function(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];var f=c+c,g=
d+d,h=e+e;c*=f;var l=d*f;d*=g;var m=e*f,k=e*g;e*=h;f*=b;g*=b;b*=h;a[0]=1-d-e;a[1]=l+b;a[2]=m-g;a[3]=0;a[4]=l-b;a[5]=1-c-e;a[6]=k+f;a[7]=0;a[8]=m+g;a[9]=k-f;a[10]=1-c-d;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},frustum:function(a,b,c,d,e,f,g){var h=1/(c-b),l=1/(e-d),m=1/(f-g);a[0]=2*f*h;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=2*f*l;a[6]=0;a[7]=0;a[8]=(c+b)*h;a[9]=(e+d)*l;a[10]=(g+f)*m;a[11]=-1;a[12]=0;a[13]=0;a[14]=g*f*2*m;a[15]=0;return a},perspective:function(a,b,c,d,e){b=1/Math.tan(b/2);a[0]=b/
c;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[11]=-1;a[12]=0;a[13]=0;a[15]=0;null!=e&&Infinity!==e?(c=1/(d-e),a[10]=(e+d)*c,a[14]=2*e*d*c):(a[10]=-1,a[14]=-2*d);return a},perspectiveFromFieldOfView:function(a,b,c,d){var e=Math.tan(b.upDegrees*Math.PI/180),f=Math.tan(b.downDegrees*Math.PI/180),g=Math.tan(b.leftDegrees*Math.PI/180);b=Math.tan(b.rightDegrees*Math.PI/180);var h=2/(g+b),l=2/(e+f);a[0]=h;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=l;a[6]=0;a[7]=0;a[8]=-((g-b)*h*.5);a[9]=(e-f)*
l*.5;a[10]=d/(c-d);a[11]=-1;a[12]=0;a[13]=0;a[14]=d*c/(c-d);a[15]=0;return a},ortho:function(a,b,c,d,e,f,g){var h=1/(b-c),l=1/(d-e),m=1/(f-g);a[0]=-2*h;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=-2*l;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=2*m;a[11]=0;a[12]=(b+c)*h;a[13]=(e+d)*l;a[14]=(g+f)*m;a[15]=1;return a},lookAt:function(a,b,c,d){var e=b[0],f=b[1];b=b[2];var g=d[0];var h=d[1];var l=d[2];var m=c[0];d=c[1];var k=c[2];if(1E-6>Math.abs(e-m)&&1E-6>Math.abs(f-d)&&1E-6>Math.abs(b-k))return ha(a);c=e-m;d=f-d;m=b-k;
var p=1/Math.hypot(c,d,m);c*=p;d*=p;m*=p;k=h*m-l*d;l=l*c-g*m;g=g*d-h*c;(p=Math.hypot(k,l,g))?(p=1/p,k*=p,l*=p,g*=p):g=l=k=0;h=d*g-m*l;var q=m*k-c*g;var r=c*l-d*k;(p=Math.hypot(h,q,r))?(p=1/p,h*=p,q*=p,r*=p):r=q=h=0;a[0]=k;a[1]=h;a[2]=c;a[3]=0;a[4]=l;a[5]=q;a[6]=d;a[7]=0;a[8]=g;a[9]=r;a[10]=m;a[11]=0;a[12]=-(k*e+l*f+g*b);a[13]=-(h*e+q*f+r*b);a[14]=-(c*e+d*f+m*b);a[15]=1;return a},targetTo:function(a,b,c,d){var e=b[0],f=b[1];b=b[2];var g=d[0],h=d[1],l=d[2];d=e-c[0];var m=f-c[1];c=b-c[2];var k=d*d+m*
m+c*c;0<k&&(k=1/Math.sqrt(k),d*=k,m*=k,c*=k);var p=h*c-l*m;l=l*d-g*c;g=g*m-h*d;k=p*p+l*l+g*g;0<k&&(k=1/Math.sqrt(k),p*=k,l*=k,g*=k);a[0]=p;a[1]=l;a[2]=g;a[3]=0;a[4]=m*g-c*l;a[5]=c*p-d*g;a[6]=d*l-m*p;a[7]=0;a[8]=d;a[9]=m;a[10]=c;a[11]=0;a[12]=e;a[13]=f;a[14]=b;a[15]=1;return a},str:function(a){return"mat4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+")"},frob:function(a){return Math.hypot(a[0],
a[1],a[3],a[4],a[5],a[6],a[7],a[8],a[9],a[10],a[11],a[12],a[13],a[14],a[15])},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];a[6]=b[6]+c[6];a[7]=b[7]+c[7];a[8]=b[8]+c[8];a[9]=b[9]+c[9];a[10]=b[10]+c[10];a[11]=b[11]+c[11];a[12]=b[12]+c[12];a[13]=b[13]+c[13];a[14]=b[14]+c[14];a[15]=b[15]+c[15];return a},subtract:na,multiplyScalar:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;a[6]=b[6]*c;a[7]=b[7]*
c;a[8]=b[8]*c;a[9]=b[9]*c;a[10]=b[10]*c;a[11]=b[11]*c;a[12]=b[12]*c;a[13]=b[13]*c;a[14]=b[14]*c;a[15]=b[15]*c;return a},multiplyScalarAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;a[4]=b[4]+c[4]*d;a[5]=b[5]+c[5]*d;a[6]=b[6]+c[6]*d;a[7]=b[7]+c[7]*d;a[8]=b[8]+c[8]*d;a[9]=b[9]+c[9]*d;a[10]=b[10]+c[10]*d;a[11]=b[11]+c[11]*d;a[12]=b[12]+c[12]*d;a[13]=b[13]+c[13]*d;a[14]=b[14]+c[14]*d;a[15]=b[15]+c[15]*d;return a},exactEquals:function(a,b){return a[0]===b[0]&&
a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===b[4]&&a[5]===b[5]&&a[6]===b[6]&&a[7]===b[7]&&a[8]===b[8]&&a[9]===b[9]&&a[10]===b[10]&&a[11]===b[11]&&a[12]===b[12]&&a[13]===b[13]&&a[14]===b[14]&&a[15]===b[15]},equals:function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],l=a[6],m=a[7],k=a[8],p=a[9],q=a[10],r=a[11],t=a[12],u=a[13],w=a[14];a=a[15];var v=b[0],x=b[1],A=b[2],B=b[3],z=b[4],E=b[5],F=b[6],G=b[7],H=b[8],I=b[9],J=b[10],K=b[11],D=b[12],L=b[13],M=b[14];b=b[15];return Math.abs(c-v)<=1E-6*Math.max(1,
Math.abs(c),Math.abs(v))&&Math.abs(d-x)<=1E-6*Math.max(1,Math.abs(d),Math.abs(x))&&Math.abs(e-A)<=1E-6*Math.max(1,Math.abs(e),Math.abs(A))&&Math.abs(f-B)<=1E-6*Math.max(1,Math.abs(f),Math.abs(B))&&Math.abs(g-z)<=1E-6*Math.max(1,Math.abs(g),Math.abs(z))&&Math.abs(h-E)<=1E-6*Math.max(1,Math.abs(h),Math.abs(E))&&Math.abs(l-F)<=1E-6*Math.max(1,Math.abs(l),Math.abs(F))&&Math.abs(m-G)<=1E-6*Math.max(1,Math.abs(m),Math.abs(G))&&Math.abs(k-H)<=1E-6*Math.max(1,Math.abs(k),Math.abs(H))&&Math.abs(p-I)<=1E-6*
Math.max(1,Math.abs(p),Math.abs(I))&&Math.abs(q-J)<=1E-6*Math.max(1,Math.abs(q),Math.abs(J))&&Math.abs(r-K)<=1E-6*Math.max(1,Math.abs(r),Math.abs(K))&&Math.abs(t-D)<=1E-6*Math.max(1,Math.abs(t),Math.abs(D))&&Math.abs(u-L)<=1E-6*Math.max(1,Math.abs(u),Math.abs(L))&&Math.abs(w-M)<=1E-6*Math.max(1,Math.abs(w),Math.abs(M))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},mul:ia,sub:na}),ca=function(){var a=Y();return function(b,c,d,e,f,g){c||(c=3);d||(d=0);for(e=e?Math.min(e*c+d,b.length):b.length;d<
e;d+=c)a[0]=b[d],a[1]=b[d+1],a[2]=b[d+2],f(a,a,g),b[d]=a[0],b[d+1]=a[1],b[d+2]=a[2];return b}}();ca=Object.freeze({create:Y,clone:function(a){var b=new v(3);b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},length:Z,fromValues:P,copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];return a},set:function(a,b,c,d){a[0]=b;a[1]=c;a[2]=d;return a},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];return a},subtract:oa,multiply:pa,divide:qa,ceil:function(a,b){a[0]=Math.ceil(b[0]);a[1]=Math.ceil(b[1]);
a[2]=Math.ceil(b[2]);return a},floor:function(a,b){a[0]=Math.floor(b[0]);a[1]=Math.floor(b[1]);a[2]=Math.floor(b[2]);return a},min:function(a,b,c){a[0]=Math.min(b[0],c[0]);a[1]=Math.min(b[1],c[1]);a[2]=Math.min(b[2],c[2]);return a},max:function(a,b,c){a[0]=Math.max(b[0],c[0]);a[1]=Math.max(b[1],c[1]);a[2]=Math.max(b[2],c[2]);return a},round:function(a,b){a[0]=Math.round(b[0]);a[1]=Math.round(b[1]);a[2]=Math.round(b[2]);return a},scale:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;return a},
scaleAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;return a},distance:ra,squaredDistance:sa,squaredLength:ta,negate:function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];return a},inverse:function(a,b){a[0]=1/b[0];a[1]=1/b[1];a[2]=1/b[2];return a},normalize:S,dot:aa,cross:T,lerp:function(a,b,c,d){var e=b[0],f=b[1];b=b[2];a[0]=e+d*(c[0]-e);a[1]=f+d*(c[1]-f);a[2]=b+d*(c[2]-b);return a},hermite:function(a,b,c,d,e,f){var g=f*f,h=g*(2*f-3)+1,l=g*(f-2)+f,m=g*(f-1);f=g*(3-2*f);a[0]=
b[0]*h+c[0]*l+d[0]*m+e[0]*f;a[1]=b[1]*h+c[1]*l+d[1]*m+e[1]*f;a[2]=b[2]*h+c[2]*l+d[2]*m+e[2]*f;return a},bezier:function(a,b,c,d,e,f){var g=1-f,h=g*g,l=f*f,m=h*g;h*=3*f;g*=3*l;f*=l;a[0]=b[0]*m+c[0]*h+d[0]*g+e[0]*f;a[1]=b[1]*m+c[1]*h+d[1]*g+e[1]*f;a[2]=b[2]*m+c[2]*h+d[2]*g+e[2]*f;return a},random:function(a,b){b=b||1;var c=2*A()*Math.PI,d=2*A()-1,e=Math.sqrt(1-d*d)*b;a[0]=Math.cos(c)*e;a[1]=Math.sin(c)*e;a[2]=d*b;return a},transformMat4:function(a,b,c){var d=b[0],e=b[1];b=b[2];var f=c[3]*d+c[7]*e+c[11]*
b+c[15];f=f||1;a[0]=(c[0]*d+c[4]*e+c[8]*b+c[12])/f;a[1]=(c[1]*d+c[5]*e+c[9]*b+c[13])/f;a[2]=(c[2]*d+c[6]*e+c[10]*b+c[14])/f;return a},transformMat3:function(a,b,c){var d=b[0],e=b[1];b=b[2];a[0]=d*c[0]+e*c[3]+b*c[6];a[1]=d*c[1]+e*c[4]+b*c[7];a[2]=d*c[2]+e*c[5]+b*c[8];return a},transformQuat:function(a,b,c){var d=c[0],e=c[1],f=c[2],g=b[0],h=b[1];b=b[2];var l=e*b-f*h,m=f*g-d*b,k=d*h-e*g;c=2*c[3];a[0]=g+l*c+2*(e*k-f*m);a[1]=h+m*c+2*(f*l-d*k);a[2]=b+k*c+2*(d*m-e*l);return a},rotateX:function(a,b,c,d){var e=
[],f=[];e[0]=b[0]-c[0];e[1]=b[1]-c[1];e[2]=b[2]-c[2];f[0]=e[0];f[1]=e[1]*Math.cos(d)-e[2]*Math.sin(d);f[2]=e[1]*Math.sin(d)+e[2]*Math.cos(d);a[0]=f[0]+c[0];a[1]=f[1]+c[1];a[2]=f[2]+c[2];return a},rotateY:function(a,b,c,d){var e=[],f=[];e[0]=b[0]-c[0];e[1]=b[1]-c[1];e[2]=b[2]-c[2];f[0]=e[2]*Math.sin(d)+e[0]*Math.cos(d);f[1]=e[1];f[2]=e[2]*Math.cos(d)-e[0]*Math.sin(d);a[0]=f[0]+c[0];a[1]=f[1]+c[1];a[2]=f[2]+c[2];return a},rotateZ:function(a,b,c,d){var e=[],f=[];e[0]=b[0]-c[0];e[1]=b[1]-c[1];e[2]=b[2]-
c[2];f[0]=e[0]*Math.cos(d)-e[1]*Math.sin(d);f[1]=e[0]*Math.sin(d)+e[1]*Math.cos(d);f[2]=e[2];a[0]=f[0]+c[0];a[1]=f[1]+c[1];a[2]=f[2]+c[2];return a},angle:function(a,b){a=P(a[0],a[1],a[2]);b=P(b[0],b[1],b[2]);S(a,a);S(b,b);b=aa(a,b);return 1<b?0:-1>b?Math.PI:Math.acos(b)},zero:function(a){a[0]=0;a[1]=0;a[2]=0;return a},str:function(a){return"vec3("+a[0]+", "+a[1]+", "+a[2]+")"},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]},equals:function(a,b){var c=a[0],d=a[1];a=a[2];var e=
b[0],f=b[1];b=b[2];return Math.abs(c-e)<=1E-6*Math.max(1,Math.abs(c),Math.abs(e))&&Math.abs(d-f)<=1E-6*Math.max(1,Math.abs(d),Math.abs(f))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},sub:oa,mul:pa,div:qa,dist:ra,sqrDist:sa,len:Z,sqrLen:ta,forEach:ca});var da=function(){var a=ua();return function(b,c,d,e,f,g){c||(c=4);d||(d=0);for(e=e?Math.min(e*c+d,b.length):b.length;d<e;d+=c)a[0]=b[d],a[1]=b[d+1],a[2]=b[d+2],a[3]=b[d+3],f(a,a,g),b[d]=a[0],b[d+1]=a[1],b[d+2]=a[2],b[d+3]=a[3];return b}}();
da=Object.freeze({create:ua,clone:va,fromValues:wa,copy:U,set:xa,add:ya,subtract:za,multiply:Aa,divide:Ba,ceil:function(a,b){a[0]=Math.ceil(b[0]);a[1]=Math.ceil(b[1]);a[2]=Math.ceil(b[2]);a[3]=Math.ceil(b[3]);return a},floor:function(a,b){a[0]=Math.floor(b[0]);a[1]=Math.floor(b[1]);a[2]=Math.floor(b[2]);a[3]=Math.floor(b[3]);return a},min:function(a,b,c){a[0]=Math.min(b[0],c[0]);a[1]=Math.min(b[1],c[1]);a[2]=Math.min(b[2],c[2]);a[3]=Math.min(b[3],c[3]);return a},max:function(a,b,c){a[0]=Math.max(b[0],
c[0]);a[1]=Math.max(b[1],c[1]);a[2]=Math.max(b[2],c[2]);a[3]=Math.max(b[3],c[3]);return a},round:function(a,b){a[0]=Math.round(b[0]);a[1]=Math.round(b[1]);a[2]=Math.round(b[2]);a[3]=Math.round(b[3]);return a},scale:ba,scaleAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;return a},distance:Ca,squaredDistance:Da,length:L,squaredLength:K,negate:function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];a[3]=-b[3];return a},inverse:function(a,b){a[0]=1/b[0];a[1]=1/b[1];
a[2]=1/b[2];a[3]=1/b[3];return a},normalize:V,dot:Q,cross:function(a,b,c,d){var e=c[0]*d[1]-c[1]*d[0],f=c[0]*d[2]-c[2]*d[0],g=c[0]*d[3]-c[3]*d[0],h=c[1]*d[2]-c[2]*d[1],l=c[1]*d[3]-c[3]*d[1];c=c[2]*d[3]-c[3]*d[2];d=b[0];var m=b[1],k=b[2];b=b[3];a[0]=m*c-k*l+b*h;a[1]=-(d*c)+k*g-b*f;a[2]=d*l-m*g+b*e;a[3]=-(d*h)+m*f-k*e;return a},lerp:Ea,random:function(a,b){b=b||1;do{var c=2*A()-1;var d=2*A()-1;var e=c*c+d*d}while(1<=e);do{var f=2*A()-1;var g=2*A()-1;var h=f*f+g*g}while(1<=h);e=Math.sqrt((1-e)/h);a[0]=
b*c;a[1]=b*d;a[2]=b*f*e;a[3]=b*g*e;return a},transformMat4:function(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];a[0]=c[0]*d+c[4]*e+c[8]*f+c[12]*b;a[1]=c[1]*d+c[5]*e+c[9]*f+c[13]*b;a[2]=c[2]*d+c[6]*e+c[10]*f+c[14]*b;a[3]=c[3]*d+c[7]*e+c[11]*f+c[15]*b;return a},transformQuat:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=c[0],h=c[1],l=c[2];c=c[3];var m=c*d+h*f-l*e,k=c*e+l*d-g*f,p=c*f+g*e-h*d;d=-g*d-h*e-l*f;a[0]=m*c+d*-g+k*-l-p*-h;a[1]=k*c+d*-h+p*-g-m*-l;a[2]=p*c+d*-l+m*-h-k*-g;a[3]=b[3];return a},zero:function(a){a[0]=
0;a[1]=0;a[2]=0;a[3]=0;return a},str:function(a){return"vec4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"},exactEquals:Fa,equals:Ga,sub:za,mul:Aa,div:Ba,dist:Ca,sqrDist:Da,len:L,sqrLen:K,forEach:da});var ea=function(){var a=Y(),b=P(1,0,0),c=P(0,1,0);return function(d,e,f){var g=aa(e,f);if(-.999999>g)return T(a,b,e),1E-6>Z(a)&&T(a,c,e),S(a,a),Ha(d,a,Math.PI),d;if(.999999<g)return d[0]=0,d[1]=0,d[2]=0,d[3]=1,d;T(a,e,f);d[0]=a[0];d[1]=a[1];d[2]=a[2];d[3]=1+g;return V(d,d)}}(),fa=function(){var a=W(),b=W();
return function(c,d,e,f,g,h){X(a,d,g,h);X(b,e,f,h);X(c,a,b,2*h*(1-h));return c}}(),R=function(){var a=B();return function(b,c,d,e){a[0]=d[0];a[3]=d[1];a[6]=d[2];a[1]=e[0];a[4]=e[1];a[7]=e[2];a[2]=-c[0];a[5]=-c[1];a[8]=-c[2];return V(b,Oa(b,a))}}();ea=Object.freeze({create:W,identity:function(a){a[0]=0;a[1]=0;a[2]=0;a[3]=1;return a},setAxisAngle:Ha,getAxisAngle:function(a,b){var c=2*Math.acos(b[3]),d=Math.sin(c/2);1E-6<d?(a[0]=b[0]/d,a[1]=b[1]/d,a[2]=b[2]/d):(a[0]=1,a[1]=0,a[2]=0);return c},getAngle:function(a,
b){a=Q(a,b);return Math.acos(2*a*a-1)},multiply:Ia,rotateX:Ja,rotateY:Ka,rotateZ:La,calculateW:function(a,b){var c=b[0],d=b[1];b=b[2];a[0]=c;a[1]=d;a[2]=b;a[3]=Math.sqrt(Math.abs(1-c*c-d*d-b*b));return a},exp:Ma,ln:Na,pow:function(a,b,c){Na(a,b);ba(a,a,c);Ma(a,a);return a},slerp:X,random:function(a){var b=A(),c=A(),d=A(),e=Math.sqrt(1-b);b=Math.sqrt(b);a[0]=e*Math.sin(2*Math.PI*c);a[1]=e*Math.cos(2*Math.PI*c);a[2]=b*Math.sin(2*Math.PI*d);a[3]=b*Math.cos(2*Math.PI*d);return a},invert:function(a,b){var c=
b[0],d=b[1],e=b[2];b=b[3];var f=c*c+d*d+e*e+b*b;f=f?1/f:0;a[0]=-c*f;a[1]=-d*f;a[2]=-e*f;a[3]=b*f;return a},conjugate:function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];a[3]=b[3];return a},fromMat3:Oa,fromEuler:function(a,b,c,d){var e=.5*Math.PI/180;b*=e;c*=e;d*=e;e=Math.sin(b);b=Math.cos(b);var f=Math.sin(c);c=Math.cos(c);var g=Math.sin(d);d=Math.cos(d);a[0]=e*c*d-b*f*g;a[1]=b*f*d+e*c*g;a[2]=b*c*g-e*f*d;a[3]=b*c*d+e*f*g;return a},str:function(a){return"quat("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"},clone:va,
fromValues:wa,copy:U,set:xa,add:ya,mul:Ia,scale:ba,dot:Q,lerp:Ea,length:L,len:L,squaredLength:K,sqrLen:K,normalize:V,exactEquals:Fa,equals:Ga,rotationTo:ea,sqlerp:fa,setAxes:R});fa=Object.freeze({create:function(){var a=new v(8);v!=Float32Array&&(a[0]=0,a[1]=0,a[2]=0,a[4]=0,a[5]=0,a[6]=0,a[7]=0);a[3]=1;return a},clone:function(a){var b=new v(8);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];return b},fromValues:function(a,b,c,d,e,f,g,h){var l=new v(8);l[0]=a;l[1]=
b;l[2]=c;l[3]=d;l[4]=e;l[5]=f;l[6]=g;l[7]=h;return l},fromRotationTranslationValues:function(a,b,c,d,e,f,g){var h=new v(8);h[0]=a;h[1]=b;h[2]=c;h[3]=d;e*=.5;f*=.5;g*=.5;h[4]=e*d+f*c-g*b;h[5]=f*d+g*a-e*c;h[6]=g*d+e*b-f*a;h[7]=-e*a-f*b-g*c;return h},fromRotationTranslation:Pa,fromTranslation:function(a,b){a[0]=0;a[1]=0;a[2]=0;a[3]=1;a[4]=.5*b[0];a[5]=.5*b[1];a[6]=.5*b[2];a[7]=0;return a},fromRotation:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=0;a[5]=0;a[6]=0;a[7]=0;return a},fromMat4:function(a,
b){var c=W();ma(c,b);var d=new v(3);ka(d,b);Pa(a,c,d);return a},copy:Qa,identity:function(a){a[0]=0;a[1]=0;a[2]=0;a[3]=1;a[4]=0;a[5]=0;a[6]=0;a[7]=0;return a},set:function(a,b,c,d,e,f,g,h,l){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=f;a[5]=g;a[6]=h;a[7]=l;return a},getReal:U,getDual:function(a,b){a[0]=b[4];a[1]=b[5];a[2]=b[6];a[3]=b[7];return a},setReal:U,setDual:function(a,b){a[4]=b[0];a[5]=b[1];a[6]=b[2];a[7]=b[3];return a},getTranslation:function(a,b){var c=b[4],d=b[5],e=b[6],f=b[7],g=-b[0],h=-b[1],l=-b[2];
b=b[3];a[0]=2*(c*b+f*g+d*l-e*h);a[1]=2*(d*b+f*h+e*g-c*l);a[2]=2*(e*b+f*l+c*h-d*g);return a},translate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=.5*c[0],l=.5*c[1];c=.5*c[2];var m=b[4],k=b[5],p=b[6];b=b[7];a[0]=d;a[1]=e;a[2]=f;a[3]=g;a[4]=g*h+e*c-f*l+m;a[5]=g*l+f*h-d*c+k;a[6]=g*c+d*l-e*h+p;a[7]=-d*h-e*l-f*c+b;return a},rotateX:function(a,b,c){var d=-b[0],e=-b[1],f=-b[2],g=b[3],h=b[4],l=b[5],m=b[6],k=b[7],p=h*g+k*d+l*f-m*e,q=l*g+k*e+m*d-h*f,r=m*g+k*f+h*e-l*d;h=k*g-h*d-l*e-m*f;Ja(a,b,c);d=a[0];
e=a[1];f=a[2];g=a[3];a[4]=p*g+h*d+q*f-r*e;a[5]=q*g+h*e+r*d-p*f;a[6]=r*g+h*f+p*e-q*d;a[7]=h*g-p*d-q*e-r*f;return a},rotateY:function(a,b,c){var d=-b[0],e=-b[1],f=-b[2],g=b[3],h=b[4],l=b[5],m=b[6],k=b[7],p=h*g+k*d+l*f-m*e,q=l*g+k*e+m*d-h*f,r=m*g+k*f+h*e-l*d;h=k*g-h*d-l*e-m*f;Ka(a,b,c);d=a[0];e=a[1];f=a[2];g=a[3];a[4]=p*g+h*d+q*f-r*e;a[5]=q*g+h*e+r*d-p*f;a[6]=r*g+h*f+p*e-q*d;a[7]=h*g-p*d-q*e-r*f;return a},rotateZ:function(a,b,c){var d=-b[0],e=-b[1],f=-b[2],g=b[3],h=b[4],l=b[5],k=b[6],n=b[7],p=h*g+n*
d+l*f-k*e,q=l*g+n*e+k*d-h*f,r=k*g+n*f+h*e-l*d;h=n*g-h*d-l*e-k*f;La(a,b,c);d=a[0];e=a[1];f=a[2];g=a[3];a[4]=p*g+h*d+q*f-r*e;a[5]=q*g+h*e+r*d-p*f;a[6]=r*g+h*f+p*e-q*d;a[7]=h*g-p*d-q*e-r*f;return a},rotateByQuatAppend:function(a,b,c){var d=c[0],e=c[1],f=c[2];c=c[3];var g=b[0],h=b[1],l=b[2],k=b[3];a[0]=g*c+k*d+h*f-l*e;a[1]=h*c+k*e+l*d-g*f;a[2]=l*c+k*f+g*e-h*d;a[3]=k*c-g*d-h*e-l*f;g=b[4];h=b[5];l=b[6];k=b[7];a[4]=g*c+k*d+h*f-l*e;a[5]=h*c+k*e+l*d-g*f;a[6]=l*c+k*f+g*e-h*d;a[7]=k*c-g*d-h*e-l*f;return a},
rotateByQuatPrepend:function(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];var g=c[0],h=c[1],l=c[2],k=c[3];a[0]=d*k+b*g+e*l-f*h;a[1]=e*k+b*h+f*g-d*l;a[2]=f*k+b*l+d*h-e*g;a[3]=b*k-d*g-e*h-f*l;g=c[4];h=c[5];l=c[6];k=c[7];a[4]=d*k+b*g+e*l-f*h;a[5]=e*k+b*h+f*g-d*l;a[6]=f*k+b*l+d*h-e*g;a[7]=b*k-d*g-e*h-f*l;return a},rotateAroundAxis:function(a,b,c,d){if(1E-6>Math.abs(d))return Qa(a,b);var e=Math.hypot(c[0],c[1],c[2]);d*=.5;var f=Math.sin(d),g=f*c[0]/e,h=f*c[1]/e;c=f*c[2]/e;d=Math.cos(d);e=b[0];f=b[1];var l=b[2],
k=b[3];a[0]=e*d+k*g+f*c-l*h;a[1]=f*d+k*h+l*g-e*c;a[2]=l*d+k*c+e*h-f*g;a[3]=k*d-e*g-f*h-l*c;e=b[4];f=b[5];l=b[6];b=b[7];a[4]=e*d+b*g+f*c-l*h;a[5]=f*d+b*h+l*g-e*c;a[6]=l*d+b*c+e*h-f*g;a[7]=b*d-e*g-f*h-l*c;return a},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];a[6]=b[6]+c[6];a[7]=b[7]+c[7];return a},multiply:Ra,mul:Ra,scale:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;a[6]=b[6]*c;a[7]=b[7]*c;return a},
dot:Q,lerp:function(a,b,c,d){var e=1-d;0>Q(b,c)&&(d=-d);a[0]=b[0]*e+c[0]*d;a[1]=b[1]*e+c[1]*d;a[2]=b[2]*e+c[2]*d;a[3]=b[3]*e+c[3]*d;a[4]=b[4]*e+c[4]*d;a[5]=b[5]*e+c[5]*d;a[6]=b[6]*e+c[6]*d;a[7]=b[7]*e+c[7]*d;return a},invert:function(a,b){var c=K(b);a[0]=-b[0]/c;a[1]=-b[1]/c;a[2]=-b[2]/c;a[3]=b[3]/c;a[4]=-b[4]/c;a[5]=-b[5]/c;a[6]=-b[6]/c;a[7]=b[7]/c;return a},conjugate:function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];a[3]=b[3];a[4]=-b[4];a[5]=-b[5];a[6]=-b[6];a[7]=b[7];return a},length:L,len:L,squaredLength:K,
sqrLen:K,normalize:function(a,b){var c=K(b);if(0<c){c=Math.sqrt(c);var d=b[0]/c,e=b[1]/c,f=b[2]/c,g=b[3]/c,h=b[4],l=b[5],k=b[6];b=b[7];var n=d*h+e*l+f*k+g*b;a[0]=d;a[1]=e;a[2]=f;a[3]=g;a[4]=(h-d*n)/c;a[5]=(l-e*n)/c;a[6]=(k-f*n)/c;a[7]=(b-g*n)/c}return a},str:function(a){return"quat2("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+")"},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===b[4]&&a[5]===b[5]&&a[6]===b[6]&&a[7]===b[7]},
equals:function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],l=a[6];a=a[7];var k=b[0],n=b[1],p=b[2],q=b[3],r=b[4],t=b[5],u=b[6];b=b[7];return Math.abs(c-k)<=1E-6*Math.max(1,Math.abs(c),Math.abs(k))&&Math.abs(d-n)<=1E-6*Math.max(1,Math.abs(d),Math.abs(n))&&Math.abs(e-p)<=1E-6*Math.max(1,Math.abs(e),Math.abs(p))&&Math.abs(f-q)<=1E-6*Math.max(1,Math.abs(f),Math.abs(q))&&Math.abs(g-r)<=1E-6*Math.max(1,Math.abs(g),Math.abs(r))&&Math.abs(h-t)<=1E-6*Math.max(1,Math.abs(h),Math.abs(t))&&Math.abs(l-
u)<=1E-6*Math.max(1,Math.abs(l),Math.abs(u))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))}});R=function(){var a=Sa();return function(b,c,d,e,f,g){c||(c=2);d||(d=0);for(e=e?Math.min(e*c+d,b.length):b.length;d<e;d+=c)a[0]=b[d],a[1]=b[d+1],f(a,a,g),b[d]=a[0],b[d+1]=a[1];return b}}();R=Object.freeze({create:Sa,clone:function(a){var b=new v(2);b[0]=a[0];b[1]=a[1];return b},fromValues:function(a,b){var c=new v(2);c[0]=a;c[1]=b;return c},copy:function(a,b){a[0]=b[0];a[1]=b[1];return a},set:function(a,
b,c){a[0]=b;a[1]=c;return a},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];return a},subtract:Ta,multiply:Ua,divide:Va,ceil:function(a,b){a[0]=Math.ceil(b[0]);a[1]=Math.ceil(b[1]);return a},floor:function(a,b){a[0]=Math.floor(b[0]);a[1]=Math.floor(b[1]);return a},min:function(a,b,c){a[0]=Math.min(b[0],c[0]);a[1]=Math.min(b[1],c[1]);return a},max:function(a,b,c){a[0]=Math.max(b[0],c[0]);a[1]=Math.max(b[1],c[1]);return a},round:function(a,b){a[0]=Math.round(b[0]);a[1]=Math.round(b[1]);return a},
scale:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;return a},scaleAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;return a},distance:Wa,squaredDistance:Xa,length:Ya,squaredLength:Za,negate:function(a,b){a[0]=-b[0];a[1]=-b[1];return a},inverse:function(a,b){a[0]=1/b[0];a[1]=1/b[1];return a},normalize:function(a,b){var c=b[0],d=b[1];c=c*c+d*d;0<c&&(c=1/Math.sqrt(c));a[0]=b[0]*c;a[1]=b[1]*c;return a},dot:function(a,b){return a[0]*b[0]+a[1]*b[1]},cross:function(a,b,c){b=b[0]*c[1]-b[1]*c[0];a[0]=
a[1]=0;a[2]=b;return a},lerp:function(a,b,c,d){var e=b[0];b=b[1];a[0]=e+d*(c[0]-e);a[1]=b+d*(c[1]-b);return a},random:function(a,b){b=b||1;var c=2*A()*Math.PI;a[0]=Math.cos(c)*b;a[1]=Math.sin(c)*b;return a},transformMat2:function(a,b,c){var d=b[0];b=b[1];a[0]=c[0]*d+c[2]*b;a[1]=c[1]*d+c[3]*b;return a},transformMat2d:function(a,b,c){var d=b[0];b=b[1];a[0]=c[0]*d+c[2]*b+c[4];a[1]=c[1]*d+c[3]*b+c[5];return a},transformMat3:function(a,b,c){var d=b[0];b=b[1];a[0]=c[0]*d+c[3]*b+c[6];a[1]=c[1]*d+c[4]*b+
c[7];return a},transformMat4:function(a,b,c){var d=b[0];b=b[1];a[0]=c[0]*d+c[4]*b+c[12];a[1]=c[1]*d+c[5]*b+c[13];return a},rotate:function(a,b,c,d){var e=b[0]-c[0];b=b[1]-c[1];var f=Math.sin(d);d=Math.cos(d);a[0]=e*d-b*f+c[0];a[1]=e*f+b*d+c[1];return a},angle:function(a,b){var c=a[0];a=a[1];var d=b[0];b=b[1];var e=c*c+a*a;0<e&&(e=1/Math.sqrt(e));var f=d*d+b*b;0<f&&(f=1/Math.sqrt(f));c=(c*d+a*b)*e*f;return 1<c?0:-1>c?Math.PI:Math.acos(c)},zero:function(a){a[0]=0;a[1]=0;return a},str:function(a){return"vec2("+
a[0]+", "+a[1]+")"},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]},equals:function(a,b){var c=a[0];a=a[1];var d=b[0];b=b[1];return Math.abs(c-d)<=1E-6*Math.max(1,Math.abs(c),Math.abs(d))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},len:Ya,sub:Ta,mul:Ua,div:Va,dist:Wa,sqrDist:Xa,sqrLen:Za,forEach:R});k.glMatrix=ab;k.mat2=bb;k.mat2d=cb;k.mat3=db;k.mat4=eb;k.quat=ea;k.quat2=fa;k.vec2=R;k.vec3=ca;k.vec4=da;Object.defineProperty(k,"__esModule",{value:!0})});
