var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(r,n,z){r!=Array.prototype&&r!=Object.prototype&&(r[n]=z.value)};$jscomp.getGlobal=function(r){return"undefined"!=typeof window&&window===r?r:"undefined"!=typeof global&&null!=global?global:r};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(r,n,z,x){if(n){z=$jscomp.global;r=r.split(".");for(x=0;x<r.length-1;x++){var w=r[x];w in z||(z[w]={});z=z[w]}r=r[r.length-1];x=z[r];n=n(x);n!=x&&null!=n&&$jscomp.defineProperty(z,r,{configurable:!0,writable:!0,value:n})}};
$jscomp.polyfill("Math.hypot",function(r){return r?r:function(n){if(2>arguments.length)return arguments.length?Math.abs(arguments[0]):0;var r,x,w;for(r=w=0;r<arguments.length;r++)w=Math.max(w,Math.abs(arguments[r]));if(1E100<w||1E-100>w){if(!w)return w;for(r=x=0;r<arguments.length;r++){var D=Number(arguments[r])/w;x+=D*D}return Math.sqrt(x)*w}for(r=x=0;r<arguments.length;r++)D=Number(arguments[r]),x+=D*D;return Math.sqrt(x)}},"es6","es3");
var keylist={},vertexShaderText="precision mediump float;\n\nattribute vec3 vertPosition;\nattribute vec3 vertColor;\nuniform mat4 mWorld;\nuniform mat4 mView;\nuniform mat4 mProj;\nvarying vec3 fragColor;\n\nvoid main()\n{\nfragColor = vertColor;\ngl_Position = mProj * mView * mWorld * vec4(vertPosition, 1.0);\n}",fragShaderText="precision mediump float;\nvarying vec3 fragColor;\nvoid main()\n{\ngl_FragColor = vec4(fragColor,1.0);\n}";
function main(){console.log("started main");var r=document.querySelector("#canvas1"),n=r.getContext("webgl");n.clearColor(0,0,0,1);n.clear(n.COLOR_BUFFER_BIT);var z=n.createShader(n.VERTEX_SHADER),x=n.createShader(n.FRAGMENT_SHADER);n.shaderSource(z,vertexShaderText);n.shaderSource(x,fragShaderText);n.compileShader(z);n.compileShader(x);if(n.getShaderParameter(z,n.COMPILE_STATUS))if(n.getShaderParameter(x,n.COMPILE_STATUS)){var w=n.createProgram();n.attachShader(w,z);n.attachShader(w,x);n.linkProgram(w);
n.getProgramParameter(w,n.LINK_STATUS)||console.error("ERROR linking program",n.getProgramInfoLog(w));n.validateProgram(w);n.getProgramParameter(w,n.VALIDATE_STATUS)||console.error("ERROR validating",n.getProgramInfoLog(w));z=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,z);n.bufferData(n.ARRAY_BUFFER,new Float32Array([0,.5,0,1,1,0,-.5,-.5,0,.7,0,.9,.5,-.5,0,.3,.5,.9]),n.STATIC_DRAW);z=n.getAttribLocation(w,"vertPosition");x=n.getAttribLocation(w,"vertColor");n.vertexAttribPointer(z,3,n.FLOAT,n.FALSE,
6*Float32Array.BYTES_PER_ELEMENT,0);n.vertexAttribPointer(x,3,n.FLOAT,n.FALSE,6*Float32Array.BYTES_PER_ELEMENT,3*Float32Array.BYTES_PER_ELEMENT);n.enableVertexAttribArray(z);n.enableVertexAttribArray(x);n.useProgram(w);z=n.getUniformLocation(w,"mWorld");x=n.getUniformLocation(w,"mView");var D=n.getUniformLocation(w,"mWProj"),K=new Float32Array(16),L=new Float32Array(16),M=new Float32Array(16);glMatrix.mat4.identity(M);glMatrix.mat4.lookAt(L,[0,0,-5],[0,0,0],[0,1,0]);glMatrix.mat4.perspective(K,glMatrix.glMatrix.toRadian(45),
r.width/r.height,.1,1E3);n.uniformMatrix4fv(z,n.FALSE,M);n.uniformMatrix4fv(x,n.FALSE,L);n.uniformMatrix4fv(D,n.FALSE,K);n.useProgram(w);n.drawArrays(n.TRIANGLES,0,3)}else console.error("ERROR compiling",n.getShaderInfoLog(x));else console.error("ERROR compiling",n.getShaderInfoLog(z))}function keypressed(r){keylist[r.key]="keydown"==r.type;keylist.s&&keylist.Alt&&main()};/*
 @fileoverview gl-matrix - High performance matrix and vector operations
@author Brandon Jones
@author Colin MacKenzie IV
@version 3.1.0

Copyright (c) 2015-2019, Brandon Jones, Colin MacKenzie IV.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

*/
(function(r,n){"object"===typeof exports&&"undefined"!==typeof module?n(exports):"function"===typeof define&&define.amd?define(["exports"],n):(r=r||self,n(r.glMatrix={}))})(this,function(r){function n(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];var g=c[0],h=c[1],k=c[2];c=c[3];a[0]=d*g+f*h;a[1]=e*g+b*h;a[2]=d*k+f*c;a[3]=e*k+b*c;return a}function z(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];return a}function x(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4];b=b[5];var k=c[0],l=c[1],
m=c[2],p=c[3],y=c[4];c=c[5];a[0]=d*k+f*l;a[1]=e*k+g*l;a[2]=d*m+f*p;a[3]=e*m+g*p;a[4]=d*y+f*c+h;a[5]=e*y+g*c+b;return a}function w(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];a[4]=b[4]-c[4];a[5]=b[5]-c[5];return a}function D(){var a=new u(9);u!=Float32Array&&(a[1]=0,a[2]=0,a[3]=0,a[5]=0,a[6]=0,a[7]=0);a[0]=1;a[4]=1;a[8]=1;return a}function K(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4],k=b[5],l=b[6],m=b[7];b=b[8];var p=c[0],y=c[1],q=c[2],n=c[3],v=c[4],t=c[5],r=c[6],E=c[7];c=
c[8];a[0]=p*d+y*g+q*l;a[1]=p*e+y*h+q*m;a[2]=p*f+y*k+q*b;a[3]=n*d+v*g+t*l;a[4]=n*e+v*h+t*m;a[5]=n*f+v*k+t*b;a[6]=r*d+E*g+c*l;a[7]=r*e+E*h+c*m;a[8]=r*f+E*k+c*b;return a}function L(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];a[4]=b[4]-c[4];a[5]=b[5]-c[5];a[6]=b[6]-c[6];a[7]=b[7]-c[7];a[8]=b[8]-c[8];return a}function M(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}function fa(a,b,c){var d=b[0],e=
b[1],f=b[2],g=b[3],h=b[4],k=b[5],l=b[6],m=b[7],p=b[8],y=b[9],q=b[10],n=b[11],v=b[12],t=b[13],r=b[14];b=b[15];var E=c[0],u=c[1],B=c[2],A=c[3];a[0]=E*d+u*h+B*p+A*v;a[1]=E*e+u*k+B*y+A*t;a[2]=E*f+u*l+B*q+A*r;a[3]=E*g+u*m+B*n+A*b;E=c[4];u=c[5];B=c[6];A=c[7];a[4]=E*d+u*h+B*p+A*v;a[5]=E*e+u*k+B*y+A*t;a[6]=E*f+u*l+B*q+A*r;a[7]=E*g+u*m+B*n+A*b;E=c[8];u=c[9];B=c[10];A=c[11];a[8]=E*d+u*h+B*p+A*v;a[9]=E*e+u*k+B*y+A*t;a[10]=E*f+u*l+B*q+A*r;a[11]=E*g+u*m+B*n+A*b;E=c[12];u=c[13];B=c[14];A=c[15];a[12]=E*d+u*h+B*
p+A*v;a[13]=E*e+u*k+B*y+A*t;a[14]=E*f+u*l+B*q+A*r;a[15]=E*g+u*m+B*n+A*b;return a}function ha(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=d+d,k=e+e,l=f+f;b=d*h;var m=d*k;d*=l;var p=e*k;e*=l;f*=l;h*=g;k*=g;g*=l;a[0]=1-(p+f);a[1]=m+g;a[2]=d-k;a[3]=0;a[4]=m-g;a[5]=1-(b+f);a[6]=e+h;a[7]=0;a[8]=d+k;a[9]=e-h;a[10]=1-(b+p);a[11]=0;a[12]=c[0];a[13]=c[1];a[14]=c[2];a[15]=1;return a}function ia(a,b){a[0]=b[12];a[1]=b[13];a[2]=b[14];return a}function ja(a,b){var c=b[4],d=b[5],e=b[6],f=b[8],g=b[9],h=b[10];a[0]=Math.hypot(b[0],
b[1],b[2]);a[1]=Math.hypot(c,d,e);a[2]=Math.hypot(f,g,h);return a}function ka(a,b){var c=new u(3);ja(c,b);var d=1/c[0],e=1/c[1],f=1/c[2],g=b[0]*d;c=b[1]*e;var h=b[2]*f,k=b[4]*d,l=b[5]*e,m=b[6]*f;d*=b[8];e*=b[9];b=b[10]*f;f=g+l+b;0<f?(g=2*Math.sqrt(f+1),a[3]=.25*g,a[0]=(m-e)/g,a[1]=(d-h)/g,a[2]=(c-k)/g):g>l&&g>b?(g=2*Math.sqrt(1+g-l-b),a[3]=(m-e)/g,a[0]=.25*g,a[1]=(c+k)/g,a[2]=(d+h)/g):l>b?(g=2*Math.sqrt(1+l-g-b),a[3]=(d-h)/g,a[0]=(c+k)/g,a[1]=.25*g,a[2]=(m+e)/g):(g=2*Math.sqrt(1+b-g-l),a[3]=(c-k)/
g,a[0]=(d+h)/g,a[1]=(m+e)/g,a[2]=.25*g);return a}function la(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];a[4]=b[4]-c[4];a[5]=b[5]-c[5];a[6]=b[6]-c[6];a[7]=b[7]-c[7];a[8]=b[8]-c[8];a[9]=b[9]-c[9];a[10]=b[10]-c[10];a[11]=b[11]-c[11];a[12]=b[12]-c[12];a[13]=b[13]-c[13];a[14]=b[14]-c[14];a[15]=b[15]-c[15];return a}function X(){var a=new u(3);u!=Float32Array&&(a[0]=0,a[1]=0,a[2]=0);return a}function Y(a){return Math.hypot(a[0],a[1],a[2])}function N(a,b,c){var d=new u(3);d[0]=a;d[1]=
b;d[2]=c;return d}function ma(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];return a}function na(a,b,c){a[0]=b[0]*c[0];a[1]=b[1]*c[1];a[2]=b[2]*c[2];return a}function oa(a,b,c){a[0]=b[0]/c[0];a[1]=b[1]/c[1];a[2]=b[2]/c[2];return a}function pa(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1],b[2]-a[2])}function qa(a,b){var c=b[0]-a[0],d=b[1]-a[1];a=b[2]-a[2];return c*c+d*d+a*a}function ra(a){var b=a[0],c=a[1];a=a[2];return b*b+c*c+a*a}function R(a,b){var c=b[0],d=b[1],e=b[2];c=c*c+d*d+e*e;0<c&&(c=
1/Math.sqrt(c));a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;return a}function Z(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}function S(a,b,c){var d=b[0],e=b[1];b=b[2];var f=c[0],g=c[1];c=c[2];a[0]=e*c-b*g;a[1]=b*f-d*c;a[2]=d*g-e*f;return a}function sa(){var a=new u(4);u!=Float32Array&&(a[0]=0,a[1]=0,a[2]=0,a[3]=0);return a}function ta(a){var b=new u(4);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b}function ua(a,b,c,d){var e=new u(4);e[0]=a;e[1]=b;e[2]=c;e[3]=d;return e}function T(a,b){a[0]=b[0];a[1]=b[1];
a[2]=b[2];a[3]=b[3];return a}function va(a,b,c,d,e){a[0]=b;a[1]=c;a[2]=d;a[3]=e;return a}function wa(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];return a}function xa(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];return a}function ya(a,b,c){a[0]=b[0]*c[0];a[1]=b[1]*c[1];a[2]=b[2]*c[2];a[3]=b[3]*c[3];return a}function za(a,b,c){a[0]=b[0]/c[0];a[1]=b[1]/c[1];a[2]=b[2]/c[2];a[3]=b[3]/c[3];return a}function aa(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=
b[3]*c;return a}function Aa(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1],b[2]-a[2],b[3]-a[3])}function Ba(a,b){var c=b[0]-a[0],d=b[1]-a[1],e=b[2]-a[2];a=b[3]-a[3];return c*c+d*d+e*e+a*a}function J(a){return Math.hypot(a[0],a[1],a[2],a[3])}function I(a){var b=a[0],c=a[1],d=a[2];a=a[3];return b*b+c*c+d*d+a*a}function U(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];var f=c*c+d*d+e*e+b*b;0<f&&(f=1/Math.sqrt(f));a[0]=c*f;a[1]=d*f;a[2]=e*f;a[3]=b*f;return a}function O(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*
b[3]}function Ca(a,b,c,d){var e=b[0],f=b[1],g=b[2];b=b[3];a[0]=e+d*(c[0]-e);a[1]=f+d*(c[1]-f);a[2]=g+d*(c[2]-g);a[3]=b+d*(c[3]-b);return a}function Da(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]}function Ea(a,b){var c=a[0],d=a[1],e=a[2];a=a[3];var f=b[0],g=b[1],h=b[2];b=b[3];return Math.abs(c-f)<=1E-6*Math.max(1,Math.abs(c),Math.abs(f))&&Math.abs(d-g)<=1E-6*Math.max(1,Math.abs(d),Math.abs(g))&&Math.abs(e-h)<=1E-6*Math.max(1,Math.abs(e),Math.abs(h))&&Math.abs(a-b)<=1E-6*Math.max(1,
Math.abs(a),Math.abs(b))}function V(){var a=new u(4);u!=Float32Array&&(a[0]=0,a[1]=0,a[2]=0);a[3]=1;return a}function Fa(a,b,c){c*=.5;var d=Math.sin(c);a[0]=d*b[0];a[1]=d*b[1];a[2]=d*b[2];a[3]=Math.cos(c);return a}function Ga(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];var g=c[0],h=c[1],k=c[2];c=c[3];a[0]=d*c+b*g+e*k-f*h;a[1]=e*c+b*h+f*g-d*k;a[2]=f*c+b*k+d*h-e*g;a[3]=b*c-d*g-e*h-f*k;return a}function Ha(a,b,c){c*=.5;var d=b[0],e=b[1],f=b[2];b=b[3];var g=Math.sin(c);c=Math.cos(c);a[0]=d*c+b*g;a[1]=e*c+
f*g;a[2]=f*c-e*g;a[3]=b*c-d*g;return a}function Ia(a,b,c){c*=.5;var d=b[0],e=b[1],f=b[2];b=b[3];var g=Math.sin(c);c=Math.cos(c);a[0]=d*c-f*g;a[1]=e*c+b*g;a[2]=f*c+d*g;a[3]=b*c-e*g;return a}function Ja(a,b,c){c*=.5;var d=b[0],e=b[1],f=b[2];b=b[3];var g=Math.sin(c);c=Math.cos(c);a[0]=d*c+e*g;a[1]=e*c-d*g;a[2]=f*c+b*g;a[3]=b*c-f*g;return a}function Ka(a,b){var c=b[0],d=b[1],e=b[2],f=Math.sqrt(c*c+d*d+e*e);b=Math.exp(b[3]);var g=0<f?b*Math.sin(f)/f:0;a[0]=c*g;a[1]=d*g;a[2]=e*g;a[3]=b*Math.cos(f);return a}
function La(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];var f=Math.sqrt(c*c+d*d+e*e);f=0<f?Math.atan2(f,b)/f:0;a[0]=c*f;a[1]=d*f;a[2]=e*f;a[3]=.5*Math.log(c*c+d*d+e*e+b*b);return a}function W(a,b,c,d){var e=b[0],f=b[1],g=b[2];b=b[3];var h=c[0],k=c[1],l=c[2];c=c[3];var m=e*h+f*k+g*l+b*c;0>m&&(m=-m,h=-h,k=-k,l=-l,c=-c);if(1E-6<1-m){var p=Math.acos(m);var y=Math.sin(p);m=Math.sin((1-d)*p)/y;d=Math.sin(d*p)/y}else m=1-d;a[0]=m*e+d*h;a[1]=m*f+d*k;a[2]=m*g+d*l;a[3]=m*b+d*c;return a}function Ma(a,b){var c=b[0]+
b[4]+b[8];if(0<c)c=Math.sqrt(c+1),a[3]=.5*c,c=.5/c,a[0]=(b[5]-b[7])*c,a[1]=(b[6]-b[2])*c,a[2]=(b[1]-b[3])*c;else{var d=0;b[4]>b[0]&&(d=1);b[8]>b[3*d+d]&&(d=2);var e=(d+1)%3,f=(d+2)%3;c=Math.sqrt(b[3*d+d]-b[3*e+e]-b[3*f+f]+1);a[d]=.5*c;c=.5/c;a[3]=(b[3*e+f]-b[3*f+e])*c;a[e]=(b[3*e+d]+b[3*d+e])*c;a[f]=(b[3*f+d]+b[3*d+f])*c}return a}function Na(a,b,c){var d=.5*c[0],e=.5*c[1];c=.5*c[2];var f=b[0],g=b[1],h=b[2];b=b[3];a[0]=f;a[1]=g;a[2]=h;a[3]=b;a[4]=d*b+e*h-c*g;a[5]=e*b+c*f-d*h;a[6]=c*b+d*g-e*f;a[7]=
-d*f-e*g-c*h;return a}function Oa(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];return a}function Pa(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=c[4],k=c[5],l=c[6],m=c[7],p=b[4],y=b[5],q=b[6];b=b[7];var n=c[0],v=c[1],t=c[2];c=c[3];a[0]=d*c+g*n+e*t-f*v;a[1]=e*c+g*v+f*n-d*t;a[2]=f*c+g*t+d*v-e*n;a[3]=g*c-d*n-e*v-f*t;a[4]=d*m+g*h+e*l-f*k+p*c+b*n+y*t-q*v;a[5]=e*m+g*k+f*h-d*l+y*c+b*v+q*n-p*t;a[6]=f*m+g*l+d*k-e*h+q*c+b*t+p*v-y*n;a[7]=g*m-d*h-e*k-f*l+b*c-p*n-y*v-q*t;return a}
function Qa(){var a=new u(2);u!=Float32Array&&(a[0]=0,a[1]=0);return a}function Ra(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];return a}function Sa(a,b,c){a[0]=b[0]*c[0];a[1]=b[1]*c[1];return a}function Ta(a,b,c){a[0]=b[0]/c[0];a[1]=b[1]/c[1];return a}function Ua(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1])}function Va(a,b){var c=b[0]-a[0];a=b[1]-a[1];return c*c+a*a}function Wa(a){return Math.hypot(a[0],a[1])}function Xa(a){var b=a[0];a=a[1];return b*b+a*a}var u="undefined"!==typeof Float32Array?Float32Array:
Array,C=Math.random,Ya=Math.PI/180;Math.hypot||(Math.hypot=function(){for(var a=0,b=arguments.length;b--;)a+=arguments[b]*arguments[b];return Math.sqrt(a)});var Za=Object.freeze({EPSILON:1E-6,get ARRAY_TYPE(){return u},RANDOM:C,setMatrixArrayType:function(a){u=a},toRadian:function(a){return a*Ya},equals:function(a,b){return Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))}}),$a=Object.freeze({create:function(){var a=new u(4);u!=Float32Array&&(a[1]=0,a[2]=0);a[0]=1;a[3]=1;return a},clone:function(a){var b=
new u(4);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];return a},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=1;return a},fromValues:function(a,b,c,d){var e=new u(4);e[0]=a;e[1]=b;e[2]=c;e[3]=d;return e},set:function(a,b,c,d,e){a[0]=b;a[1]=c;a[2]=d;a[3]=e;return a},transpose:function(a,b){if(a===b){var c=b[1];a[1]=b[2];a[2]=c}else a[0]=b[0],a[1]=b[2],a[2]=b[1],a[3]=b[3];return a},invert:function(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];
var f=c*b-e*d;if(!f)return null;f=1/f;a[0]=b*f;a[1]=-d*f;a[2]=-e*f;a[3]=c*f;return a},adjoint:function(a,b){var c=b[0];a[0]=b[3];a[1]=-b[1];a[2]=-b[2];a[3]=c;return a},determinant:function(a){return a[0]*a[3]-a[2]*a[1]},multiply:n,rotate:function(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];var g=Math.sin(c);c=Math.cos(c);a[0]=d*c+f*g;a[1]=e*c+b*g;a[2]=d*-g+f*c;a[3]=e*-g+b*c;return a},scale:function(a,b,c){var d=b[1],e=b[2],f=b[3],g=c[0];c=c[1];a[0]=b[0]*g;a[1]=d*g;a[2]=e*c;a[3]=f*c;return a},fromRotation:function(a,
b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=c;a[2]=-c;a[3]=b;return a},fromScaling:function(a,b){a[0]=b[0];a[1]=0;a[2]=0;a[3]=b[1];return a},str:function(a){return"mat2("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"},frob:function(a){return Math.hypot(a[0],a[1],a[2],a[3])},LDU:function(a,b,c,d){a[2]=d[2]/d[0];c[0]=d[0];c[1]=d[1];c[3]=d[3]-a[2]*c[1];return[a,b,c]},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];return a},subtract:z,exactEquals:function(a,b){return a[0]===
b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]},equals:function(a,b){var c=a[0],d=a[1],e=a[2];a=a[3];var f=b[0],g=b[1],h=b[2];b=b[3];return Math.abs(c-f)<=1E-6*Math.max(1,Math.abs(c),Math.abs(f))&&Math.abs(d-g)<=1E-6*Math.max(1,Math.abs(d),Math.abs(g))&&Math.abs(e-h)<=1E-6*Math.max(1,Math.abs(e),Math.abs(h))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},multiplyScalar:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;return a},multiplyScalarAndAdd:function(a,b,c,d){a[0]=b[0]+
c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;return a},mul:n,sub:z}),ab=Object.freeze({create:function(){var a=new u(6);u!=Float32Array&&(a[1]=0,a[2]=0,a[4]=0,a[5]=0);a[0]=1;a[3]=1;return a},clone:function(a){var b=new u(6);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];return b},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];return a},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=1;a[4]=0;a[5]=0;return a},fromValues:function(a,b,c,d,e,f){var g=
new u(6);g[0]=a;g[1]=b;g[2]=c;g[3]=d;g[4]=e;g[5]=f;return g},set:function(a,b,c,d,e,f,g){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=f;a[5]=g;return a},invert:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4];b=b[5];var h=c*f-d*e;if(!h)return null;h=1/h;a[0]=f*h;a[1]=-d*h;a[2]=-e*h;a[3]=c*h;a[4]=(e*b-f*g)*h;a[5]=(d*g-c*b)*h;return a},determinant:function(a){return a[0]*a[3]-a[1]*a[2]},multiply:x,rotate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4];b=b[5];var k=Math.sin(c);c=Math.cos(c);a[0]=d*c+
f*k;a[1]=e*c+g*k;a[2]=d*-k+f*c;a[3]=e*-k+g*c;a[4]=h;a[5]=b;return a},scale:function(a,b,c){var d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],k=c[0];c=c[1];a[0]=b[0]*k;a[1]=d*k;a[2]=e*c;a[3]=f*c;a[4]=g;a[5]=h;return a},translate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4];b=b[5];var k=c[0];c=c[1];a[0]=d;a[1]=e;a[2]=f;a[3]=g;a[4]=d*k+f*c+h;a[5]=e*k+g*c+b;return a},fromRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=c;a[2]=-c;a[3]=b;a[4]=0;a[5]=0;return a},fromScaling:function(a,b){a[0]=
b[0];a[1]=0;a[2]=0;a[3]=b[1];a[4]=0;a[5]=0;return a},fromTranslation:function(a,b){a[0]=1;a[1]=0;a[2]=0;a[3]=1;a[4]=b[0];a[5]=b[1];return a},str:function(a){return"mat2d("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+")"},frob:function(a){return Math.hypot(a[0],a[1],a[2],a[3],a[4],a[5],1)},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];return a},subtract:w,multiplyScalar:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=
b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;return a},multiplyScalarAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;a[4]=b[4]+c[4]*d;a[5]=b[5]+c[5]*d;return a},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===b[4]&&a[5]===b[5]},equals:function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4];a=a[5];var h=b[0],k=b[1],l=b[2],m=b[3],p=b[4];b=b[5];return Math.abs(c-h)<=1E-6*Math.max(1,Math.abs(c),Math.abs(h))&&Math.abs(d-k)<=1E-6*Math.max(1,
Math.abs(d),Math.abs(k))&&Math.abs(e-l)<=1E-6*Math.max(1,Math.abs(e),Math.abs(l))&&Math.abs(f-m)<=1E-6*Math.max(1,Math.abs(f),Math.abs(m))&&Math.abs(g-p)<=1E-6*Math.max(1,Math.abs(g),Math.abs(p))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},mul:x,sub:w}),bb=Object.freeze({create:D,fromMat4:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[4];a[4]=b[5];a[5]=b[6];a[6]=b[8];a[7]=b[9];a[8]=b[10];return a},clone:function(a){var b=new u(9);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];
b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];return a},fromValues:function(a,b,c,d,e,f,g,h,k){var l=new u(9);l[0]=a;l[1]=b;l[2]=c;l[3]=d;l[4]=e;l[5]=f;l[6]=g;l[7]=h;l[8]=k;return l},set:function(a,b,c,d,e,f,g,h,k,l){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=f;a[5]=g;a[6]=h;a[7]=k;a[8]=l;return a},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},transpose:function(a,
b){if(a===b){var c=b[1],d=b[2],e=b[5];a[1]=b[3];a[2]=b[6];a[3]=c;a[5]=b[7];a[6]=d;a[7]=e}else a[0]=b[0],a[1]=b[3],a[2]=b[6],a[3]=b[1],a[4]=b[4],a[5]=b[7],a[6]=b[2],a[7]=b[5],a[8]=b[8];return a},invert:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],k=b[6],l=b[7];b=b[8];var m=b*g-h*l,p=-b*f+h*k,y=l*f-g*k,q=c*m+d*p+e*y;if(!q)return null;q=1/q;a[0]=m*q;a[1]=(-b*d+e*l)*q;a[2]=(h*d-e*g)*q;a[3]=p*q;a[4]=(b*c-e*k)*q;a[5]=(-h*c+e*f)*q;a[6]=y*q;a[7]=(-l*c+d*k)*q;a[8]=(g*c-d*f)*q;return a},adjoint:function(a,
b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],k=b[6],l=b[7];b=b[8];a[0]=g*b-h*l;a[1]=e*l-d*b;a[2]=d*h-e*g;a[3]=h*k-f*b;a[4]=c*b-e*k;a[5]=e*f-c*h;a[6]=f*l-g*k;a[7]=d*k-c*l;a[8]=c*g-d*f;return a},determinant:function(a){var b=a[3],c=a[4],d=a[5],e=a[6],f=a[7],g=a[8];return a[0]*(g*c-d*f)+a[1]*(-g*b+d*e)+a[2]*(f*b-c*e)},multiply:K,translate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4],k=b[5],l=b[6],m=b[7];b=b[8];var p=c[0];c=c[1];a[0]=d;a[1]=e;a[2]=f;a[3]=g;a[4]=h;a[5]=k;a[6]=p*d+c*g+l;a[7]=
p*e+c*h+m;a[8]=p*f+c*k+b;return a},rotate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=b[4],k=b[5],l=b[6],m=b[7];b=b[8];var p=Math.sin(c);c=Math.cos(c);a[0]=c*d+p*g;a[1]=c*e+p*h;a[2]=c*f+p*k;a[3]=c*g-p*d;a[4]=c*h-p*e;a[5]=c*k-p*f;a[6]=l;a[7]=m;a[8]=b;return a},scale:function(a,b,c){var d=c[0];c=c[1];a[0]=d*b[0];a[1]=d*b[1];a[2]=d*b[2];a[3]=c*b[3];a[4]=c*b[4];a[5]=c*b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];return a},fromTranslation:function(a,b){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=b[0];a[7]=
b[1];a[8]=1;return a},fromRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=c;a[2]=0;a[3]=-c;a[4]=b;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},fromScaling:function(a,b){a[0]=b[0];a[1]=0;a[2]=0;a[3]=0;a[4]=b[1];a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},fromMat2d:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=0;a[3]=b[2];a[4]=b[3];a[5]=0;a[6]=b[4];a[7]=b[5];a[8]=1;return a},fromQuat:function(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];var f=c+c,g=d+d,h=e+e;c*=f;var k=d*f;d*=g;var l=e*f,m=e*g;e*=h;f*=b;g*=
b;b*=h;a[0]=1-d-e;a[3]=k-b;a[6]=l+g;a[1]=k+b;a[4]=1-c-e;a[7]=m-f;a[2]=l-g;a[5]=m+f;a[8]=1-c-d;return a},normalFromMat4:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],k=b[6],l=b[7],m=b[8],p=b[9],y=b[10],q=b[11],n=b[12],v=b[13],t=b[14];b=b[15];var r=c*h-d*g,u=c*k-e*g,w=c*l-f*g,B=d*k-e*h,A=d*l-f*h,x=e*l-f*k,z=m*v-p*n,G=m*t-y*n;m=m*b-q*n;var H=p*t-y*v;p=p*b-q*v;y=y*b-q*t;q=r*y-u*p+w*H+B*m-A*G+x*z;if(!q)return null;q=1/q;a[0]=(h*y-k*p+l*H)*q;a[1]=(k*m-g*y-l*G)*q;a[2]=(g*p-h*m+l*z)*q;a[3]=
(e*p-d*y-f*H)*q;a[4]=(c*y-e*m+f*G)*q;a[5]=(d*m-c*p-f*z)*q;a[6]=(v*x-t*A+b*B)*q;a[7]=(t*w-n*x-b*u)*q;a[8]=(n*A-v*w+b*r)*q;return a},projection:function(a,b,c){a[0]=2/b;a[1]=0;a[2]=0;a[3]=0;a[4]=-2/c;a[5]=0;a[6]=-1;a[7]=1;a[8]=1;return a},str:function(a){return"mat3("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+")"},frob:function(a){return Math.hypot(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8])},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];
a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];a[6]=b[6]+c[6];a[7]=b[7]+c[7];a[8]=b[8]+c[8];return a},subtract:L,multiplyScalar:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;a[6]=b[6]*c;a[7]=b[7]*c;a[8]=b[8]*c;return a},multiplyScalarAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;a[4]=b[4]+c[4]*d;a[5]=b[5]+c[5]*d;a[6]=b[6]+c[6]*d;a[7]=b[7]+c[7]*d;a[8]=b[8]+c[8]*d;return a},exactEquals:function(a,b){return a[0]===
b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===b[4]&&a[5]===b[5]&&a[6]===b[6]&&a[7]===b[7]&&a[8]===b[8]},equals:function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],k=a[6],l=a[7];a=a[8];var m=b[0],p=b[1],y=b[2],q=b[3],n=b[4],v=b[5],t=b[6],r=b[7];b=b[8];return Math.abs(c-m)<=1E-6*Math.max(1,Math.abs(c),Math.abs(m))&&Math.abs(d-p)<=1E-6*Math.max(1,Math.abs(d),Math.abs(p))&&Math.abs(e-y)<=1E-6*Math.max(1,Math.abs(e),Math.abs(y))&&Math.abs(f-q)<=1E-6*Math.max(1,Math.abs(f),Math.abs(q))&&Math.abs(g-
n)<=1E-6*Math.max(1,Math.abs(g),Math.abs(n))&&Math.abs(h-v)<=1E-6*Math.max(1,Math.abs(h),Math.abs(v))&&Math.abs(k-t)<=1E-6*Math.max(1,Math.abs(k),Math.abs(t))&&Math.abs(l-r)<=1E-6*Math.max(1,Math.abs(l),Math.abs(r))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},mul:K,sub:L}),cb=Object.freeze({create:function(){var a=new u(16);u!=Float32Array&&(a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[11]=0,a[12]=0,a[13]=0,a[14]=0);a[0]=1;a[5]=1;a[10]=1;a[15]=1;return a},clone:function(a){var b=
new u(16);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];a[9]=b[9];a[10]=b[10];a[11]=b[11];a[12]=b[12];a[13]=b[13];a[14]=b[14];a[15]=b[15];return a},fromValues:function(a,b,c,d,e,f,g,h,k,l,m,p,y,q,n,v){var t=new u(16);t[0]=a;t[1]=b;t[2]=c;t[3]=d;t[4]=e;t[5]=
f;t[6]=g;t[7]=h;t[8]=k;t[9]=l;t[10]=m;t[11]=p;t[12]=y;t[13]=q;t[14]=n;t[15]=v;return t},set:function(a,b,c,d,e,f,g,h,k,l,m,p,y,q,n,v,t){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=f;a[5]=g;a[6]=h;a[7]=k;a[8]=l;a[9]=m;a[10]=p;a[11]=y;a[12]=q;a[13]=n;a[14]=v;a[15]=t;return a},identity:M,transpose:function(a,b){if(a===b){var c=b[1],d=b[2],e=b[3],f=b[6],g=b[7],h=b[11];a[1]=b[4];a[2]=b[8];a[3]=b[12];a[4]=c;a[6]=b[9];a[7]=b[13];a[8]=d;a[9]=f;a[11]=b[14];a[12]=e;a[13]=g;a[14]=h}else a[0]=b[0],a[1]=b[4],a[2]=b[8],a[3]=
b[12],a[4]=b[1],a[5]=b[5],a[6]=b[9],a[7]=b[13],a[8]=b[2],a[9]=b[6],a[10]=b[10],a[11]=b[14],a[12]=b[3],a[13]=b[7],a[14]=b[11],a[15]=b[15];return a},invert:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],k=b[6],l=b[7],m=b[8],p=b[9],y=b[10],q=b[11],n=b[12],v=b[13],t=b[14];b=b[15];var r=c*h-d*g,u=c*k-e*g,w=c*l-f*g,B=d*k-e*h,A=d*l-f*h,x=e*l-f*k,z=m*v-p*n,G=m*t-y*n,H=m*b-q*n,P=p*t-y*v,C=p*b-q*v,D=y*b-q*t,F=r*D-u*C+w*P+B*H-A*G+x*z;if(!F)return null;F=1/F;a[0]=(h*D-k*C+l*P)*F;a[1]=(e*C-d*D-f*
P)*F;a[2]=(v*x-t*A+b*B)*F;a[3]=(y*A-p*x-q*B)*F;a[4]=(k*H-g*D-l*G)*F;a[5]=(c*D-e*H+f*G)*F;a[6]=(t*w-n*x-b*u)*F;a[7]=(m*x-y*w+q*u)*F;a[8]=(g*C-h*H+l*z)*F;a[9]=(d*H-c*C-f*z)*F;a[10]=(n*A-v*w+b*r)*F;a[11]=(p*w-m*A-q*r)*F;a[12]=(h*G-g*P-k*z)*F;a[13]=(c*P-d*G+e*z)*F;a[14]=(v*u-n*B-t*r)*F;a[15]=(m*B-p*u+y*r)*F;return a},adjoint:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=b[4],h=b[5],k=b[6],l=b[7],m=b[8],p=b[9],n=b[10],q=b[11],r=b[12],v=b[13],t=b[14];b=b[15];a[0]=h*(n*b-q*t)-p*(k*b-l*t)+v*(k*q-l*n);a[1]=
-(d*(n*b-q*t)-p*(e*b-f*t)+v*(e*q-f*n));a[2]=d*(k*b-l*t)-h*(e*b-f*t)+v*(e*l-f*k);a[3]=-(d*(k*q-l*n)-h*(e*q-f*n)+p*(e*l-f*k));a[4]=-(g*(n*b-q*t)-m*(k*b-l*t)+r*(k*q-l*n));a[5]=c*(n*b-q*t)-m*(e*b-f*t)+r*(e*q-f*n);a[6]=-(c*(k*b-l*t)-g*(e*b-f*t)+r*(e*l-f*k));a[7]=c*(k*q-l*n)-g*(e*q-f*n)+m*(e*l-f*k);a[8]=g*(p*b-q*v)-m*(h*b-l*v)+r*(h*q-l*p);a[9]=-(c*(p*b-q*v)-m*(d*b-f*v)+r*(d*q-f*p));a[10]=c*(h*b-l*v)-g*(d*b-f*v)+r*(d*l-f*h);a[11]=-(c*(h*q-l*p)-g*(d*q-f*p)+m*(d*l-f*h));a[12]=-(g*(p*t-n*v)-m*(h*t-k*v)+r*(h*
n-k*p));a[13]=c*(p*t-n*v)-m*(d*t-e*v)+r*(d*n-e*p);a[14]=-(c*(h*t-k*v)-g*(d*t-e*v)+r*(d*k-e*h));a[15]=c*(h*n-k*p)-g*(d*n-e*p)+m*(d*k-e*h);return a},determinant:function(a){var b=a[0],c=a[1],d=a[2],e=a[3],f=a[4],g=a[5],h=a[6],k=a[7],l=a[8],m=a[9],p=a[10],n=a[11],q=a[12],r=a[13],v=a[14];a=a[15];return(b*g-c*f)*(p*a-n*v)-(b*h-d*f)*(m*a-n*r)+(b*k-e*f)*(m*v-p*r)+(c*h-d*g)*(l*a-n*q)-(c*k-e*g)*(l*v-p*q)+(d*k-e*h)*(l*r-m*q)},multiply:fa,translate:function(a,b,c){var d=c[0],e=c[1];c=c[2];if(b===a)a[12]=b[0]*
d+b[4]*e+b[8]*c+b[12],a[13]=b[1]*d+b[5]*e+b[9]*c+b[13],a[14]=b[2]*d+b[6]*e+b[10]*c+b[14],a[15]=b[3]*d+b[7]*e+b[11]*c+b[15];else{var f=b[0];var g=b[1];var h=b[2];var k=b[3];var l=b[4];var m=b[5];var p=b[6];var n=b[7];var q=b[8];var r=b[9];var v=b[10];var t=b[11];a[0]=f;a[1]=g;a[2]=h;a[3]=k;a[4]=l;a[5]=m;a[6]=p;a[7]=n;a[8]=q;a[9]=r;a[10]=v;a[11]=t;a[12]=f*d+l*e+q*c+b[12];a[13]=g*d+m*e+r*c+b[13];a[14]=h*d+p*e+v*c+b[14];a[15]=k*d+n*e+t*c+b[15]}return a},scale:function(a,b,c){var d=c[0],e=c[1];c=c[2];
a[0]=b[0]*d;a[1]=b[1]*d;a[2]=b[2]*d;a[3]=b[3]*d;a[4]=b[4]*e;a[5]=b[5]*e;a[6]=b[6]*e;a[7]=b[7]*e;a[8]=b[8]*c;a[9]=b[9]*c;a[10]=b[10]*c;a[11]=b[11]*c;a[12]=b[12];a[13]=b[13];a[14]=b[14];a[15]=b[15];return a},rotate:function(a,b,c,d){var e=d[0],f=d[1];d=d[2];var g=Math.hypot(e,f,d);if(1E-6>g)return null;g=1/g;e*=g;f*=g;d*=g;var h=Math.sin(c);var k=Math.cos(c);var l=1-k;c=b[0];g=b[1];var m=b[2];var p=b[3];var n=b[4];var q=b[5];var r=b[6];var v=b[7];var t=b[8];var u=b[9];var w=b[10];var x=b[11];var B=
e*e*l+k;var A=f*e*l+d*h;var z=d*e*l-f*h;var C=e*f*l-d*h;var G=f*f*l+k;var H=d*f*l+e*h;var D=e*d*l+f*h;e=f*d*l-e*h;f=d*d*l+k;a[0]=c*B+n*A+t*z;a[1]=g*B+q*A+u*z;a[2]=m*B+r*A+w*z;a[3]=p*B+v*A+x*z;a[4]=c*C+n*G+t*H;a[5]=g*C+q*G+u*H;a[6]=m*C+r*G+w*H;a[7]=p*C+v*G+x*H;a[8]=c*D+n*e+t*f;a[9]=g*D+q*e+u*f;a[10]=m*D+r*e+w*f;a[11]=p*D+v*e+x*f;b!==a&&(a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);return a},rotateX:function(a,b,c){var d=Math.sin(c);c=Math.cos(c);var e=b[4],f=b[5],g=b[6],h=b[7],k=b[8],l=b[9],m=
b[10],p=b[11];b!==a&&(a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);a[4]=e*c+k*d;a[5]=f*c+l*d;a[6]=g*c+m*d;a[7]=h*c+p*d;a[8]=k*c-e*d;a[9]=l*c-f*d;a[10]=m*c-g*d;a[11]=p*c-h*d;return a},rotateY:function(a,b,c){var d=Math.sin(c);c=Math.cos(c);var e=b[0],f=b[1],g=b[2],h=b[3],k=b[8],l=b[9],m=b[10],p=b[11];b!==a&&(a[4]=b[4],a[5]=b[5],a[6]=b[6],a[7]=b[7],a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);a[0]=e*c-k*d;a[1]=f*c-l*d;a[2]=g*c-m*d;a[3]=h*c-p*d;a[8]=e*
d+k*c;a[9]=f*d+l*c;a[10]=g*d+m*c;a[11]=h*d+p*c;return a},rotateZ:function(a,b,c){var d=Math.sin(c);c=Math.cos(c);var e=b[0],f=b[1],g=b[2],h=b[3],k=b[4],l=b[5],m=b[6],p=b[7];b!==a&&(a[8]=b[8],a[9]=b[9],a[10]=b[10],a[11]=b[11],a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);a[0]=e*c+k*d;a[1]=f*c+l*d;a[2]=g*c+m*d;a[3]=h*c+p*d;a[4]=k*c-e*d;a[5]=l*c-f*d;a[6]=m*c-g*d;a[7]=p*c-h*d;return a},fromTranslation:function(a,b){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=
0;a[12]=b[0];a[13]=b[1];a[14]=b[2];a[15]=1;return a},fromScaling:function(a,b){a[0]=b[0];a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b[1];a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=b[2];a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromRotation:function(a,b,c){var d=c[0],e=c[1];c=c[2];var f=Math.hypot(d,e,c);if(1E-6>f)return null;f=1/f;d*=f;e*=f;c*=f;f=Math.sin(b);b=Math.cos(b);var g=1-b;a[0]=d*d*g+b;a[1]=e*d*g+c*f;a[2]=c*d*g-e*f;a[3]=0;a[4]=d*e*g-c*f;a[5]=e*e*g+b;a[6]=c*e*g+d*f;a[7]=0;a[8]=d*c*g+e*f;a[9]=e*c*g-
d*f;a[10]=c*c*g+b;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromXRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b;a[6]=c;a[7]=0;a[8]=0;a[9]=-c;a[10]=b;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromYRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=0;a[2]=-c;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=c;a[9]=0;a[10]=b;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromZRotation:function(a,b){var c=Math.sin(b);b=Math.cos(b);
a[0]=b;a[1]=c;a[2]=0;a[3]=0;a[4]=-c;a[5]=b;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},fromRotationTranslation:ha,fromQuat2:function(a,b){var c=new u(3),d=-b[0],e=-b[1],f=-b[2],g=b[3],h=b[4],k=b[5],l=b[6],m=b[7],p=d*d+e*e+f*f+g*g;0<p?(c[0]=2*(h*g+m*d+k*f-l*e)/p,c[1]=2*(k*g+m*e+l*d-h*f)/p,c[2]=2*(l*g+m*f+h*e-k*d)/p):(c[0]=2*(h*g+m*d+k*f-l*e),c[1]=2*(k*g+m*e+l*d-h*f),c[2]=2*(l*g+m*f+h*e-k*d));ha(a,b,c);return a},getTranslation:ia,getScaling:ja,getRotation:ka,
fromRotationTranslationScale:function(a,b,c,d){var e=b[0],f=b[1],g=b[2],h=b[3],k=e+e,l=f+f,m=g+g;b=e*k;var p=e*l;e*=m;var n=f*l;f*=m;g*=m;k*=h;l*=h;h*=m;m=d[0];var q=d[1];d=d[2];a[0]=(1-(n+g))*m;a[1]=(p+h)*m;a[2]=(e-l)*m;a[3]=0;a[4]=(p-h)*q;a[5]=(1-(b+g))*q;a[6]=(f+k)*q;a[7]=0;a[8]=(e+l)*d;a[9]=(f-k)*d;a[10]=(1-(b+n))*d;a[11]=0;a[12]=c[0];a[13]=c[1];a[14]=c[2];a[15]=1;return a},fromRotationTranslationScaleOrigin:function(a,b,c,d,e){var f=b[0],g=b[1],h=b[2],k=b[3],l=f+f,m=g+g,p=h+h;b=f*l;var n=f*m,
q=f*p;f=g*m;g*=p;var r=h*p;h=k*l;m*=k;var u=k*p,t=d[0],w=d[1];p=d[2];d=e[0];k=e[1];e=e[2];l=(1-(f+r))*t;var x=(n+u)*t;t*=q-m;n=(n-u)*w;r=(1-(b+r))*w;w*=g+h;q=(q+m)*p;g=(g-h)*p;b=(1-(b+f))*p;a[0]=l;a[1]=x;a[2]=t;a[3]=0;a[4]=n;a[5]=r;a[6]=w;a[7]=0;a[8]=q;a[9]=g;a[10]=b;a[11]=0;a[12]=c[0]+d-(l*d+n*k+q*e);a[13]=c[1]+k-(x*d+r*k+g*e);a[14]=c[2]+e-(t*d+w*k+b*e);a[15]=1;return a},fromQuat:function(a,b){var c=b[0],d=b[1],e=b[2];b=b[3];var f=c+c,g=d+d,h=e+e;c*=f;var k=d*f;d*=g;var l=e*f,m=e*g;e*=h;f*=b;g*=
b;b*=h;a[0]=1-d-e;a[1]=k+b;a[2]=l-g;a[3]=0;a[4]=k-b;a[5]=1-c-e;a[6]=m+f;a[7]=0;a[8]=l+g;a[9]=m-f;a[10]=1-c-d;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},frustum:function(a,b,c,d,e,f,g){var h=1/(c-b),k=1/(e-d),l=1/(f-g);a[0]=2*f*h;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=2*f*k;a[6]=0;a[7]=0;a[8]=(c+b)*h;a[9]=(e+d)*k;a[10]=(g+f)*l;a[11]=-1;a[12]=0;a[13]=0;a[14]=g*f*2*l;a[15]=0;return a},perspective:function(a,b,c,d,e){b=1/Math.tan(b/2);a[0]=b/c;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b;a[6]=0;a[7]=0;a[8]=0;
a[9]=0;a[11]=-1;a[12]=0;a[13]=0;a[15]=0;null!=e&&Infinity!==e?(c=1/(d-e),a[10]=(e+d)*c,a[14]=2*e*d*c):(a[10]=-1,a[14]=-2*d);return a},perspectiveFromFieldOfView:function(a,b,c,d){var e=Math.tan(b.upDegrees*Math.PI/180),f=Math.tan(b.downDegrees*Math.PI/180),g=Math.tan(b.leftDegrees*Math.PI/180);b=Math.tan(b.rightDegrees*Math.PI/180);var h=2/(g+b),k=2/(e+f);a[0]=h;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=k;a[6]=0;a[7]=0;a[8]=-((g-b)*h*.5);a[9]=(e-f)*k*.5;a[10]=d/(c-d);a[11]=-1;a[12]=0;a[13]=0;a[14]=d*c/(c-
d);a[15]=0;return a},ortho:function(a,b,c,d,e,f,g){var h=1/(b-c),k=1/(d-e),l=1/(f-g);a[0]=-2*h;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=-2*k;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=2*l;a[11]=0;a[12]=(b+c)*h;a[13]=(e+d)*k;a[14]=(g+f)*l;a[15]=1;return a},lookAt:function(a,b,c,d){var e=b[0],f=b[1];b=b[2];var g=d[0];var h=d[1];var k=d[2];var l=c[0];d=c[1];var m=c[2];if(1E-6>Math.abs(e-l)&&1E-6>Math.abs(f-d)&&1E-6>Math.abs(b-m))return M(a);c=e-l;d=f-d;l=b-m;var p=1/Math.hypot(c,d,l);c*=p;d*=p;l*=p;m=h*l-k*d;k=k*c-g*
l;g=g*d-h*c;(p=Math.hypot(m,k,g))?(p=1/p,m*=p,k*=p,g*=p):g=k=m=0;h=d*g-l*k;var n=l*m-c*g;var q=c*k-d*m;(p=Math.hypot(h,n,q))?(p=1/p,h*=p,n*=p,q*=p):q=n=h=0;a[0]=m;a[1]=h;a[2]=c;a[3]=0;a[4]=k;a[5]=n;a[6]=d;a[7]=0;a[8]=g;a[9]=q;a[10]=l;a[11]=0;a[12]=-(m*e+k*f+g*b);a[13]=-(h*e+n*f+q*b);a[14]=-(c*e+d*f+l*b);a[15]=1;return a},targetTo:function(a,b,c,d){var e=b[0],f=b[1];b=b[2];var g=d[0],h=d[1],k=d[2];d=e-c[0];var l=f-c[1];c=b-c[2];var m=d*d+l*l+c*c;0<m&&(m=1/Math.sqrt(m),d*=m,l*=m,c*=m);var p=h*c-k*l;
k=k*d-g*c;g=g*l-h*d;m=p*p+k*k+g*g;0<m&&(m=1/Math.sqrt(m),p*=m,k*=m,g*=m);a[0]=p;a[1]=k;a[2]=g;a[3]=0;a[4]=l*g-c*k;a[5]=c*p-d*g;a[6]=d*k-l*p;a[7]=0;a[8]=d;a[9]=l;a[10]=c;a[11]=0;a[12]=e;a[13]=f;a[14]=b;a[15]=1;return a},str:function(a){return"mat4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+")"},frob:function(a){return Math.hypot(a[0],a[1],a[3],a[4],a[5],a[6],a[7],a[8],a[9],a[10],
a[11],a[12],a[13],a[14],a[15])},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];a[6]=b[6]+c[6];a[7]=b[7]+c[7];a[8]=b[8]+c[8];a[9]=b[9]+c[9];a[10]=b[10]+c[10];a[11]=b[11]+c[11];a[12]=b[12]+c[12];a[13]=b[13]+c[13];a[14]=b[14]+c[14];a[15]=b[15]+c[15];return a},subtract:la,multiplyScalar:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;a[6]=b[6]*c;a[7]=b[7]*c;a[8]=b[8]*c;a[9]=b[9]*c;a[10]=b[10]*c;a[11]=
b[11]*c;a[12]=b[12]*c;a[13]=b[13]*c;a[14]=b[14]*c;a[15]=b[15]*c;return a},multiplyScalarAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;a[4]=b[4]+c[4]*d;a[5]=b[5]+c[5]*d;a[6]=b[6]+c[6]*d;a[7]=b[7]+c[7]*d;a[8]=b[8]+c[8]*d;a[9]=b[9]+c[9]*d;a[10]=b[10]+c[10]*d;a[11]=b[11]+c[11]*d;a[12]=b[12]+c[12]*d;a[13]=b[13]+c[13]*d;a[14]=b[14]+c[14]*d;a[15]=b[15]+c[15]*d;return a},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===
b[4]&&a[5]===b[5]&&a[6]===b[6]&&a[7]===b[7]&&a[8]===b[8]&&a[9]===b[9]&&a[10]===b[10]&&a[11]===b[11]&&a[12]===b[12]&&a[13]===b[13]&&a[14]===b[14]&&a[15]===b[15]},equals:function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],k=a[6],l=a[7],m=a[8],p=a[9],n=a[10],q=a[11],r=a[12],u=a[13],t=a[14];a=a[15];var w=b[0],x=b[1],z=b[2],B=b[3],A=b[4],C=b[5],D=b[6],G=b[7],H=b[8],I=b[9],J=b[10],K=b[11],F=b[12],L=b[13],M=b[14];b=b[15];return Math.abs(c-w)<=1E-6*Math.max(1,Math.abs(c),Math.abs(w))&&Math.abs(d-
x)<=1E-6*Math.max(1,Math.abs(d),Math.abs(x))&&Math.abs(e-z)<=1E-6*Math.max(1,Math.abs(e),Math.abs(z))&&Math.abs(f-B)<=1E-6*Math.max(1,Math.abs(f),Math.abs(B))&&Math.abs(g-A)<=1E-6*Math.max(1,Math.abs(g),Math.abs(A))&&Math.abs(h-C)<=1E-6*Math.max(1,Math.abs(h),Math.abs(C))&&Math.abs(k-D)<=1E-6*Math.max(1,Math.abs(k),Math.abs(D))&&Math.abs(l-G)<=1E-6*Math.max(1,Math.abs(l),Math.abs(G))&&Math.abs(m-H)<=1E-6*Math.max(1,Math.abs(m),Math.abs(H))&&Math.abs(p-I)<=1E-6*Math.max(1,Math.abs(p),Math.abs(I))&&
Math.abs(n-J)<=1E-6*Math.max(1,Math.abs(n),Math.abs(J))&&Math.abs(q-K)<=1E-6*Math.max(1,Math.abs(q),Math.abs(K))&&Math.abs(r-F)<=1E-6*Math.max(1,Math.abs(r),Math.abs(F))&&Math.abs(u-L)<=1E-6*Math.max(1,Math.abs(u),Math.abs(L))&&Math.abs(t-M)<=1E-6*Math.max(1,Math.abs(t),Math.abs(M))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},mul:fa,sub:la}),ba=function(){var a=X();return function(b,c,d,e,f,g){c||(c=3);d||(d=0);for(e=e?Math.min(e*c+d,b.length):b.length;d<e;d+=c)a[0]=b[d],a[1]=b[d+1],
a[2]=b[d+2],f(a,a,g),b[d]=a[0],b[d+1]=a[1],b[d+2]=a[2];return b}}();ba=Object.freeze({create:X,clone:function(a){var b=new u(3);b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},length:Y,fromValues:N,copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];return a},set:function(a,b,c,d){a[0]=b;a[1]=c;a[2]=d;return a},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];return a},subtract:ma,multiply:na,divide:oa,ceil:function(a,b){a[0]=Math.ceil(b[0]);a[1]=Math.ceil(b[1]);a[2]=Math.ceil(b[2]);return a},
floor:function(a,b){a[0]=Math.floor(b[0]);a[1]=Math.floor(b[1]);a[2]=Math.floor(b[2]);return a},min:function(a,b,c){a[0]=Math.min(b[0],c[0]);a[1]=Math.min(b[1],c[1]);a[2]=Math.min(b[2],c[2]);return a},max:function(a,b,c){a[0]=Math.max(b[0],c[0]);a[1]=Math.max(b[1],c[1]);a[2]=Math.max(b[2],c[2]);return a},round:function(a,b){a[0]=Math.round(b[0]);a[1]=Math.round(b[1]);a[2]=Math.round(b[2]);return a},scale:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;return a},scaleAndAdd:function(a,b,c,d){a[0]=
b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;return a},distance:pa,squaredDistance:qa,squaredLength:ra,negate:function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];return a},inverse:function(a,b){a[0]=1/b[0];a[1]=1/b[1];a[2]=1/b[2];return a},normalize:R,dot:Z,cross:S,lerp:function(a,b,c,d){var e=b[0],f=b[1];b=b[2];a[0]=e+d*(c[0]-e);a[1]=f+d*(c[1]-f);a[2]=b+d*(c[2]-b);return a},hermite:function(a,b,c,d,e,f){var g=f*f,h=g*(2*f-3)+1,k=g*(f-2)+f,l=g*(f-1);f=g*(3-2*f);a[0]=b[0]*h+c[0]*k+d[0]*l+e[0]*f;a[1]=b[1]*
h+c[1]*k+d[1]*l+e[1]*f;a[2]=b[2]*h+c[2]*k+d[2]*l+e[2]*f;return a},bezier:function(a,b,c,d,e,f){var g=1-f,h=g*g,k=f*f,l=h*g;h*=3*f;g*=3*k;f*=k;a[0]=b[0]*l+c[0]*h+d[0]*g+e[0]*f;a[1]=b[1]*l+c[1]*h+d[1]*g+e[1]*f;a[2]=b[2]*l+c[2]*h+d[2]*g+e[2]*f;return a},random:function(a,b){b=b||1;var c=2*C()*Math.PI,d=2*C()-1,e=Math.sqrt(1-d*d)*b;a[0]=Math.cos(c)*e;a[1]=Math.sin(c)*e;a[2]=d*b;return a},transformMat4:function(a,b,c){var d=b[0],e=b[1];b=b[2];var f=c[3]*d+c[7]*e+c[11]*b+c[15];f=f||1;a[0]=(c[0]*d+c[4]*
e+c[8]*b+c[12])/f;a[1]=(c[1]*d+c[5]*e+c[9]*b+c[13])/f;a[2]=(c[2]*d+c[6]*e+c[10]*b+c[14])/f;return a},transformMat3:function(a,b,c){var d=b[0],e=b[1];b=b[2];a[0]=d*c[0]+e*c[3]+b*c[6];a[1]=d*c[1]+e*c[4]+b*c[7];a[2]=d*c[2]+e*c[5]+b*c[8];return a},transformQuat:function(a,b,c){var d=c[0],e=c[1],f=c[2],g=b[0],h=b[1];b=b[2];var k=e*b-f*h,l=f*g-d*b,m=d*h-e*g;c=2*c[3];a[0]=g+k*c+2*(e*m-f*l);a[1]=h+l*c+2*(f*k-d*m);a[2]=b+m*c+2*(d*l-e*k);return a},rotateX:function(a,b,c,d){var e=[],f=[];e[0]=b[0]-c[0];e[1]=
b[1]-c[1];e[2]=b[2]-c[2];f[0]=e[0];f[1]=e[1]*Math.cos(d)-e[2]*Math.sin(d);f[2]=e[1]*Math.sin(d)+e[2]*Math.cos(d);a[0]=f[0]+c[0];a[1]=f[1]+c[1];a[2]=f[2]+c[2];return a},rotateY:function(a,b,c,d){var e=[],f=[];e[0]=b[0]-c[0];e[1]=b[1]-c[1];e[2]=b[2]-c[2];f[0]=e[2]*Math.sin(d)+e[0]*Math.cos(d);f[1]=e[1];f[2]=e[2]*Math.cos(d)-e[0]*Math.sin(d);a[0]=f[0]+c[0];a[1]=f[1]+c[1];a[2]=f[2]+c[2];return a},rotateZ:function(a,b,c,d){var e=[],f=[];e[0]=b[0]-c[0];e[1]=b[1]-c[1];e[2]=b[2]-c[2];f[0]=e[0]*Math.cos(d)-
e[1]*Math.sin(d);f[1]=e[0]*Math.sin(d)+e[1]*Math.cos(d);f[2]=e[2];a[0]=f[0]+c[0];a[1]=f[1]+c[1];a[2]=f[2]+c[2];return a},angle:function(a,b){a=N(a[0],a[1],a[2]);b=N(b[0],b[1],b[2]);R(a,a);R(b,b);b=Z(a,b);return 1<b?0:-1>b?Math.PI:Math.acos(b)},zero:function(a){a[0]=0;a[1]=0;a[2]=0;return a},str:function(a){return"vec3("+a[0]+", "+a[1]+", "+a[2]+")"},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]},equals:function(a,b){var c=a[0],d=a[1];a=a[2];var e=b[0],f=b[1];b=b[2];return Math.abs(c-
e)<=1E-6*Math.max(1,Math.abs(c),Math.abs(e))&&Math.abs(d-f)<=1E-6*Math.max(1,Math.abs(d),Math.abs(f))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},sub:ma,mul:na,div:oa,dist:pa,sqrDist:qa,len:Y,sqrLen:ra,forEach:ba});var ca=function(){var a=sa();return function(b,c,d,e,f,g){c||(c=4);d||(d=0);for(e=e?Math.min(e*c+d,b.length):b.length;d<e;d+=c)a[0]=b[d],a[1]=b[d+1],a[2]=b[d+2],a[3]=b[d+3],f(a,a,g),b[d]=a[0],b[d+1]=a[1],b[d+2]=a[2],b[d+3]=a[3];return b}}();ca=Object.freeze({create:sa,clone:ta,
fromValues:ua,copy:T,set:va,add:wa,subtract:xa,multiply:ya,divide:za,ceil:function(a,b){a[0]=Math.ceil(b[0]);a[1]=Math.ceil(b[1]);a[2]=Math.ceil(b[2]);a[3]=Math.ceil(b[3]);return a},floor:function(a,b){a[0]=Math.floor(b[0]);a[1]=Math.floor(b[1]);a[2]=Math.floor(b[2]);a[3]=Math.floor(b[3]);return a},min:function(a,b,c){a[0]=Math.min(b[0],c[0]);a[1]=Math.min(b[1],c[1]);a[2]=Math.min(b[2],c[2]);a[3]=Math.min(b[3],c[3]);return a},max:function(a,b,c){a[0]=Math.max(b[0],c[0]);a[1]=Math.max(b[1],c[1]);a[2]=
Math.max(b[2],c[2]);a[3]=Math.max(b[3],c[3]);return a},round:function(a,b){a[0]=Math.round(b[0]);a[1]=Math.round(b[1]);a[2]=Math.round(b[2]);a[3]=Math.round(b[3]);return a},scale:aa,scaleAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;return a},distance:Aa,squaredDistance:Ba,length:J,squaredLength:I,negate:function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];a[3]=-b[3];return a},inverse:function(a,b){a[0]=1/b[0];a[1]=1/b[1];a[2]=1/b[2];a[3]=1/b[3];return a},
normalize:U,dot:O,cross:function(a,b,c,d){var e=c[0]*d[1]-c[1]*d[0],f=c[0]*d[2]-c[2]*d[0],g=c[0]*d[3]-c[3]*d[0],h=c[1]*d[2]-c[2]*d[1],k=c[1]*d[3]-c[3]*d[1];c=c[2]*d[3]-c[3]*d[2];d=b[0];var l=b[1],m=b[2];b=b[3];a[0]=l*c-m*k+b*h;a[1]=-(d*c)+m*g-b*f;a[2]=d*k-l*g+b*e;a[3]=-(d*h)+l*f-m*e;return a},lerp:Ca,random:function(a,b){b=b||1;do{var c=2*C()-1;var d=2*C()-1;var e=c*c+d*d}while(1<=e);do{var f=2*C()-1;var g=2*C()-1;var h=f*f+g*g}while(1<=h);e=Math.sqrt((1-e)/h);a[0]=b*c;a[1]=b*d;a[2]=b*f*e;a[3]=b*
g*e;return a},transformMat4:function(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];a[0]=c[0]*d+c[4]*e+c[8]*f+c[12]*b;a[1]=c[1]*d+c[5]*e+c[9]*f+c[13]*b;a[2]=c[2]*d+c[6]*e+c[10]*f+c[14]*b;a[3]=c[3]*d+c[7]*e+c[11]*f+c[15]*b;return a},transformQuat:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=c[0],h=c[1],k=c[2];c=c[3];var l=c*d+h*f-k*e,m=c*e+k*d-g*f,p=c*f+g*e-h*d;d=-g*d-h*e-k*f;a[0]=l*c+d*-g+m*-k-p*-h;a[1]=m*c+d*-h+p*-g-l*-k;a[2]=p*c+d*-k+l*-h-m*-g;a[3]=b[3];return a},zero:function(a){a[0]=0;a[1]=0;a[2]=0;a[3]=
0;return a},str:function(a){return"vec4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"},exactEquals:Da,equals:Ea,sub:xa,mul:ya,div:za,dist:Aa,sqrDist:Ba,len:J,sqrLen:I,forEach:ca});var da=function(){var a=X(),b=N(1,0,0),c=N(0,1,0);return function(d,e,f){var g=Z(e,f);if(-.999999>g)return S(a,b,e),1E-6>Y(a)&&S(a,c,e),R(a,a),Fa(d,a,Math.PI),d;if(.999999<g)return d[0]=0,d[1]=0,d[2]=0,d[3]=1,d;S(a,e,f);d[0]=a[0];d[1]=a[1];d[2]=a[2];d[3]=1+g;return U(d,d)}}(),ea=function(){var a=V(),b=V();return function(c,d,
e,f,g,h){W(a,d,g,h);W(b,e,f,h);W(c,a,b,2*h*(1-h));return c}}(),Q=function(){var a=D();return function(b,c,d,e){a[0]=d[0];a[3]=d[1];a[6]=d[2];a[1]=e[0];a[4]=e[1];a[7]=e[2];a[2]=-c[0];a[5]=-c[1];a[8]=-c[2];return U(b,Ma(b,a))}}();da=Object.freeze({create:V,identity:function(a){a[0]=0;a[1]=0;a[2]=0;a[3]=1;return a},setAxisAngle:Fa,getAxisAngle:function(a,b){var c=2*Math.acos(b[3]),d=Math.sin(c/2);1E-6<d?(a[0]=b[0]/d,a[1]=b[1]/d,a[2]=b[2]/d):(a[0]=1,a[1]=0,a[2]=0);return c},getAngle:function(a,b){a=O(a,
b);return Math.acos(2*a*a-1)},multiply:Ga,rotateX:Ha,rotateY:Ia,rotateZ:Ja,calculateW:function(a,b){var c=b[0],d=b[1];b=b[2];a[0]=c;a[1]=d;a[2]=b;a[3]=Math.sqrt(Math.abs(1-c*c-d*d-b*b));return a},exp:Ka,ln:La,pow:function(a,b,c){La(a,b);aa(a,a,c);Ka(a,a);return a},slerp:W,random:function(a){var b=C(),c=C(),d=C(),e=Math.sqrt(1-b);b=Math.sqrt(b);a[0]=e*Math.sin(2*Math.PI*c);a[1]=e*Math.cos(2*Math.PI*c);a[2]=b*Math.sin(2*Math.PI*d);a[3]=b*Math.cos(2*Math.PI*d);return a},invert:function(a,b){var c=b[0],
d=b[1],e=b[2];b=b[3];var f=c*c+d*d+e*e+b*b;f=f?1/f:0;a[0]=-c*f;a[1]=-d*f;a[2]=-e*f;a[3]=b*f;return a},conjugate:function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];a[3]=b[3];return a},fromMat3:Ma,fromEuler:function(a,b,c,d){var e=.5*Math.PI/180;b*=e;c*=e;d*=e;e=Math.sin(b);b=Math.cos(b);var f=Math.sin(c);c=Math.cos(c);var g=Math.sin(d);d=Math.cos(d);a[0]=e*c*d-b*f*g;a[1]=b*f*d+e*c*g;a[2]=b*c*g-e*f*d;a[3]=b*c*d+e*f*g;return a},str:function(a){return"quat("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"},clone:ta,
fromValues:ua,copy:T,set:va,add:wa,mul:Ga,scale:aa,dot:O,lerp:Ca,length:J,len:J,squaredLength:I,sqrLen:I,normalize:U,exactEquals:Da,equals:Ea,rotationTo:da,sqlerp:ea,setAxes:Q});ea=Object.freeze({create:function(){var a=new u(8);u!=Float32Array&&(a[0]=0,a[1]=0,a[2]=0,a[4]=0,a[5]=0,a[6]=0,a[7]=0);a[3]=1;return a},clone:function(a){var b=new u(8);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];return b},fromValues:function(a,b,c,d,e,f,g,h){var k=new u(8);k[0]=a;k[1]=
b;k[2]=c;k[3]=d;k[4]=e;k[5]=f;k[6]=g;k[7]=h;return k},fromRotationTranslationValues:function(a,b,c,d,e,f,g){var h=new u(8);h[0]=a;h[1]=b;h[2]=c;h[3]=d;e*=.5;f*=.5;g*=.5;h[4]=e*d+f*c-g*b;h[5]=f*d+g*a-e*c;h[6]=g*d+e*b-f*a;h[7]=-e*a-f*b-g*c;return h},fromRotationTranslation:Na,fromTranslation:function(a,b){a[0]=0;a[1]=0;a[2]=0;a[3]=1;a[4]=.5*b[0];a[5]=.5*b[1];a[6]=.5*b[2];a[7]=0;return a},fromRotation:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=0;a[5]=0;a[6]=0;a[7]=0;return a},fromMat4:function(a,
b){var c=V();ka(c,b);var d=new u(3);ia(d,b);Na(a,c,d);return a},copy:Oa,identity:function(a){a[0]=0;a[1]=0;a[2]=0;a[3]=1;a[4]=0;a[5]=0;a[6]=0;a[7]=0;return a},set:function(a,b,c,d,e,f,g,h,k){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=f;a[5]=g;a[6]=h;a[7]=k;return a},getReal:T,getDual:function(a,b){a[0]=b[4];a[1]=b[5];a[2]=b[6];a[3]=b[7];return a},setReal:T,setDual:function(a,b){a[4]=b[0];a[5]=b[1];a[6]=b[2];a[7]=b[3];return a},getTranslation:function(a,b){var c=b[4],d=b[5],e=b[6],f=b[7],g=-b[0],h=-b[1],k=-b[2];
b=b[3];a[0]=2*(c*b+f*g+d*k-e*h);a[1]=2*(d*b+f*h+e*g-c*k);a[2]=2*(e*b+f*k+c*h-d*g);return a},translate:function(a,b,c){var d=b[0],e=b[1],f=b[2],g=b[3],h=.5*c[0],k=.5*c[1];c=.5*c[2];var l=b[4],m=b[5],p=b[6];b=b[7];a[0]=d;a[1]=e;a[2]=f;a[3]=g;a[4]=g*h+e*c-f*k+l;a[5]=g*k+f*h-d*c+m;a[6]=g*c+d*k-e*h+p;a[7]=-d*h-e*k-f*c+b;return a},rotateX:function(a,b,c){var d=-b[0],e=-b[1],f=-b[2],g=b[3],h=b[4],k=b[5],l=b[6],m=b[7],p=h*g+m*d+k*f-l*e,n=k*g+m*e+l*d-h*f,q=l*g+m*f+h*e-k*d;h=m*g-h*d-k*e-l*f;Ha(a,b,c);d=a[0];
e=a[1];f=a[2];g=a[3];a[4]=p*g+h*d+n*f-q*e;a[5]=n*g+h*e+q*d-p*f;a[6]=q*g+h*f+p*e-n*d;a[7]=h*g-p*d-n*e-q*f;return a},rotateY:function(a,b,c){var d=-b[0],e=-b[1],f=-b[2],g=b[3],h=b[4],k=b[5],l=b[6],m=b[7],p=h*g+m*d+k*f-l*e,n=k*g+m*e+l*d-h*f,q=l*g+m*f+h*e-k*d;h=m*g-h*d-k*e-l*f;Ia(a,b,c);d=a[0];e=a[1];f=a[2];g=a[3];a[4]=p*g+h*d+n*f-q*e;a[5]=n*g+h*e+q*d-p*f;a[6]=q*g+h*f+p*e-n*d;a[7]=h*g-p*d-n*e-q*f;return a},rotateZ:function(a,b,c){var d=-b[0],e=-b[1],f=-b[2],g=b[3],h=b[4],k=b[5],l=b[6],m=b[7],n=h*g+m*
d+k*f-l*e,r=k*g+m*e+l*d-h*f,q=l*g+m*f+h*e-k*d;h=m*g-h*d-k*e-l*f;Ja(a,b,c);d=a[0];e=a[1];f=a[2];g=a[3];a[4]=n*g+h*d+r*f-q*e;a[5]=r*g+h*e+q*d-n*f;a[6]=q*g+h*f+n*e-r*d;a[7]=h*g-n*d-r*e-q*f;return a},rotateByQuatAppend:function(a,b,c){var d=c[0],e=c[1],f=c[2];c=c[3];var g=b[0],h=b[1],k=b[2],l=b[3];a[0]=g*c+l*d+h*f-k*e;a[1]=h*c+l*e+k*d-g*f;a[2]=k*c+l*f+g*e-h*d;a[3]=l*c-g*d-h*e-k*f;g=b[4];h=b[5];k=b[6];l=b[7];a[4]=g*c+l*d+h*f-k*e;a[5]=h*c+l*e+k*d-g*f;a[6]=k*c+l*f+g*e-h*d;a[7]=l*c-g*d-h*e-k*f;return a},
rotateByQuatPrepend:function(a,b,c){var d=b[0],e=b[1],f=b[2];b=b[3];var g=c[0],h=c[1],k=c[2],l=c[3];a[0]=d*l+b*g+e*k-f*h;a[1]=e*l+b*h+f*g-d*k;a[2]=f*l+b*k+d*h-e*g;a[3]=b*l-d*g-e*h-f*k;g=c[4];h=c[5];k=c[6];l=c[7];a[4]=d*l+b*g+e*k-f*h;a[5]=e*l+b*h+f*g-d*k;a[6]=f*l+b*k+d*h-e*g;a[7]=b*l-d*g-e*h-f*k;return a},rotateAroundAxis:function(a,b,c,d){if(1E-6>Math.abs(d))return Oa(a,b);var e=Math.hypot(c[0],c[1],c[2]);d*=.5;var f=Math.sin(d),g=f*c[0]/e,h=f*c[1]/e;c=f*c[2]/e;d=Math.cos(d);e=b[0];f=b[1];var k=b[2],
l=b[3];a[0]=e*d+l*g+f*c-k*h;a[1]=f*d+l*h+k*g-e*c;a[2]=k*d+l*c+e*h-f*g;a[3]=l*d-e*g-f*h-k*c;e=b[4];f=b[5];k=b[6];b=b[7];a[4]=e*d+b*g+f*c-k*h;a[5]=f*d+b*h+k*g-e*c;a[6]=k*d+b*c+e*h-f*g;a[7]=b*d-e*g-f*h-k*c;return a},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];a[6]=b[6]+c[6];a[7]=b[7]+c[7];return a},multiply:Pa,mul:Pa,scale:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;a[6]=b[6]*c;a[7]=b[7]*c;return a},
dot:O,lerp:function(a,b,c,d){var e=1-d;0>O(b,c)&&(d=-d);a[0]=b[0]*e+c[0]*d;a[1]=b[1]*e+c[1]*d;a[2]=b[2]*e+c[2]*d;a[3]=b[3]*e+c[3]*d;a[4]=b[4]*e+c[4]*d;a[5]=b[5]*e+c[5]*d;a[6]=b[6]*e+c[6]*d;a[7]=b[7]*e+c[7]*d;return a},invert:function(a,b){var c=I(b);a[0]=-b[0]/c;a[1]=-b[1]/c;a[2]=-b[2]/c;a[3]=b[3]/c;a[4]=-b[4]/c;a[5]=-b[5]/c;a[6]=-b[6]/c;a[7]=b[7]/c;return a},conjugate:function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];a[3]=b[3];a[4]=-b[4];a[5]=-b[5];a[6]=-b[6];a[7]=b[7];return a},length:J,len:J,squaredLength:I,
sqrLen:I,normalize:function(a,b){var c=I(b);if(0<c){c=Math.sqrt(c);var d=b[0]/c,e=b[1]/c,f=b[2]/c,g=b[3]/c,h=b[4],k=b[5],l=b[6];b=b[7];var m=d*h+e*k+f*l+g*b;a[0]=d;a[1]=e;a[2]=f;a[3]=g;a[4]=(h-d*m)/c;a[5]=(k-e*m)/c;a[6]=(l-f*m)/c;a[7]=(b-g*m)/c}return a},str:function(a){return"quat2("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+")"},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===b[4]&&a[5]===b[5]&&a[6]===b[6]&&a[7]===b[7]},
equals:function(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],k=a[6];a=a[7];var l=b[0],m=b[1],n=b[2],r=b[3],q=b[4],u=b[5],v=b[6];b=b[7];return Math.abs(c-l)<=1E-6*Math.max(1,Math.abs(c),Math.abs(l))&&Math.abs(d-m)<=1E-6*Math.max(1,Math.abs(d),Math.abs(m))&&Math.abs(e-n)<=1E-6*Math.max(1,Math.abs(e),Math.abs(n))&&Math.abs(f-r)<=1E-6*Math.max(1,Math.abs(f),Math.abs(r))&&Math.abs(g-q)<=1E-6*Math.max(1,Math.abs(g),Math.abs(q))&&Math.abs(h-u)<=1E-6*Math.max(1,Math.abs(h),Math.abs(u))&&Math.abs(k-
v)<=1E-6*Math.max(1,Math.abs(k),Math.abs(v))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))}});Q=function(){var a=Qa();return function(b,c,d,e,f,g){c||(c=2);d||(d=0);for(e=e?Math.min(e*c+d,b.length):b.length;d<e;d+=c)a[0]=b[d],a[1]=b[d+1],f(a,a,g),b[d]=a[0],b[d+1]=a[1];return b}}();Q=Object.freeze({create:Qa,clone:function(a){var b=new u(2);b[0]=a[0];b[1]=a[1];return b},fromValues:function(a,b){var c=new u(2);c[0]=a;c[1]=b;return c},copy:function(a,b){a[0]=b[0];a[1]=b[1];return a},set:function(a,
b,c){a[0]=b;a[1]=c;return a},add:function(a,b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];return a},subtract:Ra,multiply:Sa,divide:Ta,ceil:function(a,b){a[0]=Math.ceil(b[0]);a[1]=Math.ceil(b[1]);return a},floor:function(a,b){a[0]=Math.floor(b[0]);a[1]=Math.floor(b[1]);return a},min:function(a,b,c){a[0]=Math.min(b[0],c[0]);a[1]=Math.min(b[1],c[1]);return a},max:function(a,b,c){a[0]=Math.max(b[0],c[0]);a[1]=Math.max(b[1],c[1]);return a},round:function(a,b){a[0]=Math.round(b[0]);a[1]=Math.round(b[1]);return a},
scale:function(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;return a},scaleAndAdd:function(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;return a},distance:Ua,squaredDistance:Va,length:Wa,squaredLength:Xa,negate:function(a,b){a[0]=-b[0];a[1]=-b[1];return a},inverse:function(a,b){a[0]=1/b[0];a[1]=1/b[1];return a},normalize:function(a,b){var c=b[0],d=b[1];c=c*c+d*d;0<c&&(c=1/Math.sqrt(c));a[0]=b[0]*c;a[1]=b[1]*c;return a},dot:function(a,b){return a[0]*b[0]+a[1]*b[1]},cross:function(a,b,c){b=b[0]*c[1]-b[1]*c[0];a[0]=
a[1]=0;a[2]=b;return a},lerp:function(a,b,c,d){var e=b[0];b=b[1];a[0]=e+d*(c[0]-e);a[1]=b+d*(c[1]-b);return a},random:function(a,b){b=b||1;var c=2*C()*Math.PI;a[0]=Math.cos(c)*b;a[1]=Math.sin(c)*b;return a},transformMat2:function(a,b,c){var d=b[0];b=b[1];a[0]=c[0]*d+c[2]*b;a[1]=c[1]*d+c[3]*b;return a},transformMat2d:function(a,b,c){var d=b[0];b=b[1];a[0]=c[0]*d+c[2]*b+c[4];a[1]=c[1]*d+c[3]*b+c[5];return a},transformMat3:function(a,b,c){var d=b[0];b=b[1];a[0]=c[0]*d+c[3]*b+c[6];a[1]=c[1]*d+c[4]*b+
c[7];return a},transformMat4:function(a,b,c){var d=b[0];b=b[1];a[0]=c[0]*d+c[4]*b+c[12];a[1]=c[1]*d+c[5]*b+c[13];return a},rotate:function(a,b,c,d){var e=b[0]-c[0];b=b[1]-c[1];var f=Math.sin(d);d=Math.cos(d);a[0]=e*d-b*f+c[0];a[1]=e*f+b*d+c[1];return a},angle:function(a,b){var c=a[0];a=a[1];var d=b[0];b=b[1];var e=c*c+a*a;0<e&&(e=1/Math.sqrt(e));var f=d*d+b*b;0<f&&(f=1/Math.sqrt(f));c=(c*d+a*b)*e*f;return 1<c?0:-1>c?Math.PI:Math.acos(c)},zero:function(a){a[0]=0;a[1]=0;return a},str:function(a){return"vec2("+
a[0]+", "+a[1]+")"},exactEquals:function(a,b){return a[0]===b[0]&&a[1]===b[1]},equals:function(a,b){var c=a[0];a=a[1];var d=b[0];b=b[1];return Math.abs(c-d)<=1E-6*Math.max(1,Math.abs(c),Math.abs(d))&&Math.abs(a-b)<=1E-6*Math.max(1,Math.abs(a),Math.abs(b))},len:Wa,sub:Ra,mul:Sa,div:Ta,dist:Ua,sqrDist:Va,sqrLen:Xa,forEach:Q});r.glMatrix=Za;r.mat2=$a;r.mat2d=ab;r.mat3=bb;r.mat4=cb;r.quat=da;r.quat2=ea;r.vec2=Q;r.vec3=ba;r.vec4=ca;Object.defineProperty(r,"__esModule",{value:!0})});
